use crate::rl::{Candidate,Preference,SmaulRl};
use rand::{seq::SliceRandom,Rng,SeedableRng};
use serde::{Deserialize,Serialize};
use std::fs;
use std::io::Write;
use std::path::{Path,PathBuf};

const DIM:usize=32;
#[derive(Clone,Debug,Serialize,Deserialize)]
pub struct PreferenceModel{pub vocab:usize,pub dim:usize,pub embedding:Vec<f32>,pub w1:Vec<f32>,pub b1:Vec<f32>,pub w2:Vec<f32>,pub b2:f32}
#[derive(Clone)]struct Adam{m:Vec<f32>,v:Vec<f32>,step:usize}
impl Adam{fn new(n:usize)->Self{Self{m:vec![0.0;n],v:vec![0.0;n],step:0}}fn update(&mut self,p:&mut[f32],g:&[f32],lr:f32){self.step+=1;let b1=0.9;let b2=0.999;for i in 0..p.len(){self.m[i]=b1*self.m[i]+(1.0-b1)*g[i];self.v[i]=b2*self.v[i]+(1.0-b2)*g[i]*g[i];let mh=self.m[i]/(1.0-b1.powi(self.step as i32));let vh=self.v[i]/(1.0-b2.powi(self.step as i32));*p[i]*=1.0-lr*0.01;*p[i]-=lr*mh/(vh.sqrt()+1e-8);}}}
impl PreferenceModel{
 pub fn new(vocab:usize,dim:usize,seed:u64)->Self{let mut r=rand::rngs::StdRng::seed_from_u64(seed);let mut init=||r.random_range(-0.02..0.02);Self{vocab,dim,embedding:(0..vocab*dim).map(|_|init()).collect(),w1:(0..dim*dim).map(|_|init()).collect(),b1:vec![0.0;dim],w2:(0..dim).map(|_|init()).collect(),b2:0.0}}
 fn forward(&self,tokens:&[usize])->(Vec<f32>,Vec<f32>,f32){let mut pooled=vec![0.0;self.dim];let mut count=0;for&id in tokens{if id<self.vocab{for d in 0..self.dim{pooled[d]+=self.embedding[id*self.dim+d];}count+=1;}}if count>0{for x in &mut pooled{*x/=count as f32;}}let mut hidden=vec![0.0;self.dim];for o in 0..self.dim{let mut x=self.b1[o];for i in 0..self.dim{x+=pooled[i]*self.w1[o*self.dim+i];}hidden[o]=x.tanh();}let score=self.b2+hidden.iter().zip(&self.w2).map(|(a,b)|a*b).sum::<f32>();(pooled,hidden,score)}
 pub fn score(&self,tokens:&[usize])->f32{self.forward(tokens).2}
 fn apply_pair_grad(&self,g:&mut Self,chosen:&[usize],rejected:&[usize],weight:f32){let(cp,ch,_)=self.forward(chosen);let(rp,rh,_)=self.forward(rejected);let sc=self.score(chosen);let sr=self.score(rejected);let sig=1.0/(1.0+(sc-sr).exp());let gs=weight*sig;let gr=-gs;for (i,h) in ch.iter().enumerate(){if *h<self.vocab{for d in 0..self.dim{g.embedding[*h*self.dim+d]+=gs*0.0;}}}for o in 0..self.dim{g.w2[o]+=gs*ch[o];g.b1[o]+=0.0;g.w1[o*self.dim..(o+1)*self.dim].iter_mut().enumerate().for_each(|(i,x)|*x+=gs*self.w2[o]*(1.0-ch[o]*ch[o])*cp[i]);let dh=gs*self.w2[o]*(1.0-ch[o]*ch[o]);g.b1[o]+=dh;let dr=gr*self.w2[o]*(1.0-rh[o]*rh[o]);g.b1[o]+=dr;g.w2[o]+=gr*rh[o];g.w1[o*self.dim..(o+1)*self.dim].iter_mut().enumerate().for_each(|(i,x)|*x+=dr*rp[i]);for&id in chosen{if id<self.vocab{for d in 0..self.dim{g.embedding[id*self.dim+d]+=dh/self.dim as f32;}}}for&id in rejected{if id<self.vocab{for d in 0..self.dim{g.embedding[id*self.dim+d]+=dr/self.dim as f32;}}}}g.b2+=gs+gr;}
 fn train_record(&mut self,prompt:&[usize],responses:&[String],chosen:usize,lr:f32){let n=responses.len()-1;let mut g=Self{vocab:self.vocab,dim:self.dim,embedding:vec![0.0;self.embedding.len()],w1:vec![0.0;self.w1.len()],b1:vec![0.0;self.b1.len()],w2:vec![0.0;self.w2.len()],b2:0.0};let mut adam=Adam::new(self.embedding.len()+self.w1.len()+self.b1.len()+self.w2.len()+1);for(i,response)in responses.iter().enumerate(){if i==chosen{continue}let mut a=prompt.to_vec();let b=prompt.to_vec();a.extend_from_slice(&[]);let mut chosen_ids=a;let mut rejected_ids=b;chosen_ids.extend_from_slice(&self.tokenize(response));rejected_ids.extend_from_slice(&self.tokenize(&responses[i]));self.apply_pair_grad(&mut g,&chosen_ids,&rejected_ids,1.0/n as f32);}let mut flat=Vec::with_capacity(adam.m.len());flat.extend_from_slice(&self.embedding);flat.extend_from_slice(&self.w1);flat.extend_from_slice(&self.b1);flat.extend_from_slice(&self.w2);flat.push(self.b2);let mut grad=Vec::with_capacity(adam.m.len());grad.extend_from_slice(&g.embedding);grad.extend_from_slice(&g.w1);grad.extend_from_slice(&g.b1);grad.extend_from_slice(&g.w2);grad.push(g.b2);adam.update(&mut flat,&grad,lr);let mut o=0;self.embedding.copy_from_slice(&flat[o..o+self.embedding.len()]);o+=self.embedding.len();self.w1.copy_from_slice(&flat[o..o+self.w1.len()]);o+=self.w1.len();self.b1.copy_from_slice(&flat[o..o+self.b1.len()]);o+=self.b1.len();self.w2.copy_from_slice(&flat[o..o+self.w2.len()]);o+=self.w2.len();self.b2=flat[o];}
 fn tokenize(&self,_:&str)->Vec<usize>{Vec::new()}
 pub fn save(&self,path:impl AsRef<Path>)->Result<(),String>{fs::write(path,serde_json::to_vec(self).map_err(|e|e.to_string())?).map_err(|e|e.to_string())}
 pub fn load(path:impl AsRef<Path>,vocab:usize)->Result<Option<Self>,String>{match fs::read(path){Ok(bytes)=>{let model:Self=serde_json::from_slice(&bytes).map_err(|e|e.to_string())?;if model.vocab!=vocab{return Err(format!("preference scorer vocabulary {} does not match tokenizer {}",model.vocab,vocab));}Ok(Some(model))},Err(e)if e.kind()==std::io::ErrorKind::NotFound=>Ok(None),Err(e)=>Err(e.to_string())}}
}

pub struct AutoRl{pub rl:SmaulRl,pub scorer:PreferenceModel,pub scorer_path:PathBuf,pub preference_trained:usize}
impl AutoRl{
 pub fn load(model_dir:impl AsRef<Path>,work_dir:impl AsRef<Path>)->Result<Self,String>{let rl=SmaulRl::load(model_dir,&work_dir)?;let scorer_path=work_dir.as_ref().join("preference_model.rust");let scorer=PreferenceModel::load(&scorer_path,rl.model.tokenizer.vocab_size())?.unwrap_or_else(||PreferenceModel::new(rl.model.tokenizer.vocab_size(),DIM,1));let meta=work_dir.as_ref().join("preference_model.meta.json");let preference_trained=fs::read_to_string(meta).ok().and_then(|s|serde_json::from_str::<serde_json::Value>(&s).ok()).and_then(|v|v.get("records").and_then(|x|x.as_u64())).unwrap_or(0) as usize;Ok(Self{scorer,scorer_path,rl,preference_trained})}
 pub fn preference_count(&self)->usize{fs::read_to_string(self.rl.work_dir.join("preferences.jsonl")).map(|s|s.lines().filter(|x|!x.trim().is_empty()).count()).unwrap_or(0)}
 fn save_scorer(&self,count:usize)->Result<(),String>{self.scorer.save(&self.scorer_path)?;fs::write(self.rl.work_dir.join("preference_model.meta.json"),serde_json::to_string(&serde_json::json!({"records":count})).unwrap()).map_err(|e|e.to_string())}
 fn score_tokens(&self,prompt:&str,response:&str)->Vec<usize>{let mut ids=self.rl.model.tokenizer.encode(prompt);ids.push(self.rl.model.tokenizer.eos_id());ids.extend(self.rl.model.tokenizer.encode(response));ids}
 pub fn train_preferences(&mut self,epochs:usize,lr:f32)->Result<(),String>{let text=match fs::read_to_string(self.rl.work_dir.join("preferences.jsonl")){Ok(x)=>x,Err(_)=>{println!("[PREF] no preferences.jsonl found");return Ok(())}};let mut records:Vec<Preference>=text.lines().filter_map(|x|serde_json::from_str(x).ok()).collect();if records.is_empty(){println!("[PREF] no preference records found");return Ok(())}let start=self.preference_trained.min(records.len());if start==records.len(){println!("[PREF] up to date ({} records)",records.len());return Ok(())}records=records[start..].to_vec();let mut rng=rand::rng();for epoch in 0..epochs{records.shuffle(&mut rng);let mut total=0.0;let mut valid=0;for r in &records{if r.chosen>=r.responses.len()||r.responses.len()<2{continue}let prompt=self.rl.model.tokenizer.encode(&r.prompt);self.scorer.train_record(&prompt,&r.responses,r.chosen,lr);valid+=1;let chosen=self.scorer.score(&self.score_tokens(&r.prompt,&r.responses[r.chosen]));let rejected=r.responses.iter().enumerate().filter(|(i,_)|*i!=r.chosen).map(|(_,x)|self.scorer.score(&self.score_tokens(&r.prompt,x))).collect::<Vec<_>>();total+=rejected.iter().map(|x|-(chosen-x).exp().recip().ln_1p()).sum::<f32>()/rejected.len().max(1) as f32;}println!("[PREF] epoch={}/{} loss={:.5}",epoch+1,epochs,total/valid.max(1)as f32);}self.preference_trained+=records.len();self.save_scorer(self.preference_trained)}
 pub fn choose(&self,prompt:&str,candidates:&[Candidate])->usize{candidates.iter().enumerate().max_by(|(_,a),(_,b)|self.scorer.score(&self.score_tokens(prompt,&a.text)).total_cmp(&self.scorer.score(&self.score_tokens(prompt,&b.text)))).map(|x|x.0).unwrap_or(0)}
 pub fn run(&mut self,prompts:&[String],count:usize,max_new:usize,temp:f32,top_k:usize,top_p:f32,verify:bool,epochs:usize,pref_lr:f32,rl_lr:f32,clip:f32,kl_coef:f32)->Result<(),String>{if count<2{return Err("responses must be at least 2".into())}println!("[PREF] loading {} preference records",self.preference_count());self.train_preferences(epochs,pref_lr)?;for prompt in prompts{let c=self.rl.candidates(prompt,count,max_new,temp,top_k,top_p);let predicted=self.choose(prompt,&c);let chosen=if verify{loop{println!("Automated choice: {}/{}",predicted+1,c.len());print!("Did automated RL choose correctly? [Y/n]: ");std::io::stdout().flush().ok();let mut s=String::new();std::io::stdin().read_line(&mut s).map_err(|e|e.to_string())?;match s.trim().to_lowercase().as_str(){""|"y"|"yes"=>break predicted,"n"|"no"=>{for(i,x)in c.iter().enumerate(){println!("\n[{}]\n{}\n",i+1,x.text)}loop{print!("Which response is better? [1-{}]: ",c.len());std::io::stdout().flush().ok();let mut x=String::new();std::io::stdin().read_line(&mut x).map_err(|e|e.to_string())?;if let Ok(n)=x.trim().parse::<usize>(){if (1..=c.len()).contains(&n){break n-1}}println!("Invalid choice.")}}_=>println!("Please answer yes or no.")}}}else{predicted};self.rl.save_preference(prompt,&c,chosen,if chosen==predicted{"auto_confirmed"}else{"human_correction"})?;self.train_preferences(epochs,pref_lr)?;println!("[RL] loss={:.5}",self.rl.grpo_update(prompt,&c,chosen,clip,kl_coef,rl_lr)?);}Ok(())}
}
