use crate::rwkv_model::RwkvModelConfig;
use serde_json::{json, Value};
use std::fs;
use std::path::Path;

#[derive(Clone, Debug)]
pub struct RwkvXConfig {
    pub vocab_size: usize, pub n_embd: usize, pub n_layer: usize, pub head_size: usize,
    pub n_moba_layer: usize, pub moba_chunk_size: usize, pub moba_topk: usize, pub dropout: f32,
    pub head_size_divisor: usize, pub ctx_len_hint: usize, pub wkv_chunk_size: usize, pub checkpoint_ffn: bool,
    pub is_moe: bool, pub num_experts: usize, pub num_experts_per_tok: usize, pub qat_3bit: bool, pub qat_bits: u8,
}
impl Default for RwkvXConfig { fn default()->Self{Self{vocab_size:65530,n_embd:832,n_layer:17,head_size:64,n_moba_layer:5,moba_chunk_size:512,moba_topk:4,dropout:0.0,head_size_divisor:8,ctx_len_hint:2048,wkv_chunk_size:64,checkpoint_ffn:true,is_moe:false,num_experts:1,num_experts_per_tok:1,qat_3bit:false,qat_bits:0}} }
impl RwkvXConfig {
 pub fn validate(&self)->Result<(),String>{if self.vocab_size==0{return Err("vocab_size must be positive".into())}if self.n_embd==0{return Err("n_embd must be positive".into())}if self.n_layer==0{return Err("n_layer must be positive".into())}if self.head_size==0||self.n_embd%self.head_size!=0{return Err(format!("n_embd ({}) must be divisible by head_size ({})",self.n_embd,self.head_size))}if self.n_moba_layer>=self.n_layer{return Err(format!("n_moba_layer ({}) must be smaller than n_layer ({})",self.n_moba_layer,self.n_layer))}if self.moba_chunk_size==0||self.moba_topk==0||self.head_size_divisor==0||self.ctx_len_hint==0||self.wkv_chunk_size==0{return Err("model sizing parameters must be positive".into())}if !self.dropout.is_finite()||!(0.0..1.0).contains(&self.dropout){return Err("dropout must be finite and in [0, 1)".into())}if self.is_moe{if self.num_experts==0{return Err("num_experts must be positive for MoE".into())}if self.num_experts_per_tok==0||self.num_experts_per_tok>self.num_experts{return Err(format!("num_experts_per_tok ({}) must be in 1..={}",self.num_experts))}}else if self.num_experts!=1||self.num_experts_per_tok!=1{return Err("non-MoE config must use num_experts=1 and num_experts_per_tok=1".into())}if self.qat_bits!=0&&!matches!(self.qat_bits,2|4|8){return Err("qat_bits must be 0, 2, 4, or 8".into())}if self.qat_3bit&&self.qat_bits!=0{return Err("qat_3bit and qat_bits cannot both be enabled".into())}Ok(())}
 pub fn effective_qat_bits(&self)->u8{if self.qat_3bit{3}else{self.qat_bits}}
 pub fn to_model_config(&self)->RwkvModelConfig{self.validate().expect("invalid RWKV-X configuration");let mut c=RwkvModelConfig::new(self.vocab_size,self.n_embd,self.n_layer,self.head_size);c.head_size_divisor=self.head_size_divisor;c.is_moe=self.is_moe;c.num_experts=self.num_experts;c.num_experts_per_tok=self.num_experts_per_tok;c.qat_bits=self.effective_qat_bits();c.with_moba(self.n_moba_layer,self.moba_chunk_size,self.moba_topk)}
 pub fn from_model_config(c:&RwkvModelConfig)->Self{Self{vocab_size:c.vocab_size,n_embd:c.n_embd,n_layer:c.n_layer,head_size:c.head_size,n_moba_layer:c.n_moba_layer,moba_chunk_size:c.moba_chunk_size,moba_topk:c.moba_topk,head_size_divisor:c.head_size_divisor,is_moe:c.is_moe,num_experts:c.num_experts,num_experts_per_tok:c.num_experts_per_tok,qat_3bit:c.qat_bits==3,qat_bits:if c.qat_bits==3{0}else{c.qat_bits},..Self::default()}}
 pub fn config_for_target_params(target_params:usize,vocab_size:usize,n_embd:usize,n_moba_layer:usize,head_size:usize)->Result<Self,String>{if head_size==0||n_embd%head_size!=0{return Err(format!("n_embd ({n_embd}) must be divisible by head_size ({head_size})"))}let mut best=None;for n_layer in 4..80{let c=Self{vocab_size,n_embd,n_layer,n_moba_layer:n_moba_layer.min(n_layer-1),head_size,..Self::default()};let d=c.approx_param_count().abs_diff(target_params);if best.as_ref().map_or(true,|(bd,_):(usize,Self)|d<*bd){best=Some((d,c));}}Ok(best.unwrap().1)}
 pub fn approx_param_count(&self)->usize{let c=self.n_embd;let v=self.vocab_size;let l=self.n_layer;let dd=(1.8*(c as f64).sqrt()/32.0).round().max(1.0)as usize*32;let dm=(1.3*(c as f64).sqrt()/32.0).round().max(1.0)as usize*32;let dg=(0.6*(c as f64).powf(0.8)/32.0).round().max(1.0)as usize*32;let tmix=4*c*c+c*(4*dd+2*dm+2*dg);let cmix=8*c*c;let rwkv=l-self.n_moba_layer;let cmix_total=if self.is_moe{rwkv*(self.num_experts*cmix+self.num_experts*c*c)}else{rwkv*cmix};2*v*c+rwkv*tmix+cmix_total+self.n_moba_layer*(4*c*c+cmix)}
 pub fn save(&self,path:impl AsRef<Path>)->Result<(),String>{self.validate()?;let v=json!({"vocab_size":self.vocab_size,"n_embd":self.n_embd,"n_layer":self.n_layer,"head_size":self.head_size,"n_moba_layer":self.n_moba_layer,"moba_chunk_size":self.moba_chunk_size,"moba_topk":self.moba_topk,"dropout":self.dropout,"head_size_divisor":self.head_size_divisor,"ctx_len_hint":self.ctx_len_hint,"wkv_chunk_size":self.wkv_chunk_size,"checkpoint_ffn":self.checkpoint_ffn,"is_moe":self.is_moe,"num_experts":self.num_experts,"num_experts_per_tok":self.num_experts_per_tok,"qat_3bit":self.qat_3bit,"qat_bits":self.qat_bits});fs::write(path,serde_json::to_string_pretty(&v).map_err(|e|e.to_string())?).map_err(|e|e.to_string())}
 pub fn load(path:impl AsRef<Path>)->Result<Self,String>{let text=fs::read_to_string(path).map_err(|e|e.to_string())?;let r:Value=serde_json::from_str(&text).map_err(|e|e.to_string())?;let legacy=bool_field(&r,"qat_3bit",false)?;let bits=usize_field(&r,"qat_bits",0)? as u8;let c=Self{vocab_size:usize_field(&r,"vocab_size",65530)?,n_embd:usize_field(&r,"n_embd",832)?,n_layer:usize_field(&r,"n_layer",17)?,head_size:usize_field(&r,"head_size",64)?,n_moba_layer:usize_field(&r,"n_moba_layer",5)?,moba_chunk_size:usize_field(&r,"moba_chunk_size",512)?,moba_topk:usize_field(&r,"moba_topk",4)?,dropout:float_field(&r,"dropout",0.0)?,head_size_divisor:usize_field(&r,"head_size_divisor",8)?,ctx_len_hint:usize_field(&r,"ctx_len_hint",2048)?,wkv_chunk_size:usize_field(&r,"wkv_chunk_size",64)?,checkpoint_ffn:bool_field(&r,"checkpoint_ffn",true)?,is_moe:bool_field(&r,"is_moe",false)?,num_experts:usize_field(&r,"num_experts",1)?,num_experts_per_tok:usize_field(&r,"num_experts_per_tok",1)?,qat_3bit:legacy||bits==3,qat_bits:if bits==3{0}else{bits}};c.validate()?;Ok(c)}
}
fn usize_field(r:&Value,n:&str,d:usize)->Result<usize,String>{match r.get(n){None=>Ok(d),Some(v)=>v.as_u64().map(|x|x as usize).ok_or_else(||format!("config field '{n}' must be an integer"))}}
fn float_field(r:&Value,n:&str,d:f32)->Result<f32,String>{match r.get(n){None=>Ok(d),Some(v)=>v.as_f64().map(|x|x as f32).ok_or_else(||format!("config field '{n}' must be a number"))}}
fn bool_field(r:&Value,n:&str,d:bool)->Result<bool,String>{match r.get(n){None=>Ok(d),Some(v)=>v.as_bool().ok_or_else(||format!("config field '{n}' must be boolean"))}}
#[cfg(test)]mod tests{use super::*;#[test]fn qat_bits_round_trip(){let p=std::env::temp_dir().join("smaul-rwkv-qat-bits.json");let mut c=RwkvXConfig::default();c.qat_bits=8;c.save(&p).unwrap();let d=RwkvXConfig::load(&p).unwrap();assert_eq!(d.qat_bits,8);assert_eq!(d.effective_qat_bits(),8);let _=std::fs::remove_file(p);}#[test]fn python_style_qat_metadata_is_accepted(){let p=std::env::temp_dir().join("smaul-rwkv-python-qat.json");fs::write(&p,r#"{"vocab_size":32,"n_embd":16,"n_layer":2,"head_size":4,"n_moba_layer":0,"qat_bits":4}"#).unwrap();let c=RwkvXConfig::load(&p).unwrap();assert_eq!(c.qat_bits,4);let _=fs::remove_file(p);}}
