use std::fs;
use std::path::Path;
use serde_json::Value;
use safetensors::{SafeTensors,Dtype};
use crate::gguf_writer::{Writer,Tensor};

fn f32_to_f16(x:f32)->u16{let b=x.to_bits();let s=((b>>16)&0x8000)as u16;let e=((b>>23)&255)as i32-127+15;let m=b&0x7fffff;if e<=0{if e< -10{return s}return s|(((m|0x800000)>>(1-e)+0x1000)>>13)as u16}if e>=31{return s|0x7c00}s|((e as u16)<<10)|((m+0x1000)>>13)as u16}
fn f32_bytes_to_f16(b:&[u8])->Vec<u8>{let mut o=Vec::with_capacity(b.len()/2);for c in b.chunks_exact(4){o.extend(f32_to_f16(f32::from_le_bytes(c.try_into().unwrap())).to_le_bytes())}o}
fn tokens(path:&Path)->Result<Vec<String>,String>{let v:Value=serde_json::from_slice(&fs::read(path).map_err(|e|e.to_string())?).map_err(|e|e.to_string())?;let x=v.get("vocab").or_else(||v.get("model").and_then(|m|m.get("vocab"))).ok_or("tokenizer.json has no vocabulary")?.as_object().ok_or("invalid tokenizer vocabulary")?;let max=x.values().filter_map(|v|v.as_u64()).max().ok_or("empty tokenizer")? as usize;let mut out=vec![String::new();max+1];for(k,id)in x{out[id.as_u64().ok_or("invalid tokenizer id")? as usize]=k.clone()}if out.iter().any(|s|s.is_empty()){return Err("tokenizer vocabulary contains gaps or empty tokens".into())}Ok(out)}
fn cfg_u32(w:&mut Writer,c:&Value,key:&str,out:&str){if let Some(v)=c.get(key).and_then(|v|v.as_u64()){w.add_meta_u32(out,v as u32)}}

pub fn convert(input_dir:impl AsRef<Path>,output:impl AsRef<Path>,dtype:&str)->Result<(),String>{if dtype!="f16"&&dtype!="f32"{return Err("dtype must be f16 or f32".into())}let dir=input_dir.as_ref();let cfg:Value=serde_json::from_slice(&fs::read(dir.join("config.json")).map_err(|e|e.to_string())?).map_err(|e|e.to_string())?;let toks=tokens(&dir.join("tokenizer.json"))?;if cfg.get("vocab_size").and_then(|v|v.as_u64()).unwrap_or(0)as usize!=toks.len(){return Err("tokenizer vocabulary does not match config vocab_size".into())}let bytes=fs::read(dir.join("model.safetensors")).map_err(|e|e.to_string())?;let st=SafeTensors::deserialize(&bytes).map_err(|e|e.to_string())?;let mut w=Writer::new();w.add_meta_str("general.name","SmaulNative RWKV-X");w.add_meta_str("general.description","RWKV-X checkpoint exported from SmaulNative");w.add_meta_u32("general.alignment",32);w.add_meta_str("general.architecture","rwkv_x");cfg_u32(&mut w,&cfg,"vocab_size","rwkv_x.vocab_size");cfg_u32(&mut w,&cfg,"ctx_len_hint","rwkv_x.context_length");cfg_u32(&mut w,&cfg,"n_embd","rwkv_x.embedding_length");cfg_u32(&mut w,&cfg,"n_layer","rwkv_x.block_count");if let Some(n)=cfg.get("n_embd").and_then(|v|v.as_u64()){if let Some(h)=cfg.get("head_size").and_then(|v|v.as_u64()){w.add_meta_u32("rwkv_x.head_count",(n/h)as u32);w.add_meta_u32("rwkv_x.head_count_kv",(n/h)as u32)}}cfg_u32(&mut w,&cfg,"head_size","rwkv_x.head_size");cfg_u32(&mut w,&cfg,"n_moba_layer","rwkv_x.n_moba_layer");cfg_u32(&mut w,&cfg,"moba_chunk_size","rwkv_x.moba_chunk_size");cfg_u32(&mut w,&cfg,"moba_topk","rwkv_x.moba_topk");cfg_u32(&mut w,&cfg,"wkv_chunk_size","rwkv_x.wkv_chunk_size");cfg_u32(&mut w,&cfg,"head_size_divisor","rwkv_x.head_size_divisor");w.add_meta_bool("rwkv_x.is_moe",cfg.get("is_moe").and_then(|v|v.as_bool()).unwrap_or(false));cfg_u32(&mut w,&cfg,"num_experts","rwkv_x.num_experts");cfg_u32(&mut w,&cfg,"num_experts_per_tok","rwkv_x.num_experts_per_tok");w.add_meta_str("tokenizer.ggml.model","rwkv");w.add_tokens("tokenizer.ggml.tokens",&toks);
for name in st.names(){let t=st.tensor(name).map_err(|e|e.to_string())?;let (data,ty)=match t.dtype(){Dtype::F32=>{if dtype=="f16"{(f32_bytes_to_f16(t.data()),1)}else{(t.data().to_vec(),0)}},Dtype::F16=>(t.data().to_vec(),1),Dtype::I8=>(t.data().to_vec(),24),Dtype::I16=>(t.data().to_vec(),25),Dtype::I32=>(t.data().to_vec(),26),Dtype::I64=>(t.data().to_vec(),27),Dtype::U8=>(t.data().to_vec(),24),Dtype::BOOL=>(t.data().to_vec(),24),other=>return Err(format!("unsupported Safetensors dtype for {name}: {other:?}"))};let shape=t.shape().iter().map(|&x|x as u64).collect::<Vec<_>>();w.tensor(Tensor{name,shape:&shape,dtype:ty,data:&data});}w.finish(output.as_ref().to_str().ok_or("invalid output path")?)?;Ok(())}

pub fn convert_cli(args:&[String])->Result<(),String>{if args.len()<3{return Err("usage: smaul-convert-gguf <input_dir> <output.gguf> [--dtype f16|f32]".into())}let dtype=if args.len()>=5&&args[3]=="--dtype"{&args[4]}else{"f16"};convert(&args[1],&args[2],dtype)}
