use crate::rwkv_model::RwkvModel;
use ndarray::{Array1, Array2};
use safetensors::tensor::{serialize_to_file,Dtype,TensorView};
use std::collections::HashMap;
use std::path::Path;
fn bytes_1d(a:&Array1<f32>)->Vec<u8>{a.iter().flat_map(|v|v.to_le_bytes()).collect()}fn bytes_2d(a:&Array2<f32>)->Vec<u8>{let a=a.as_standard_layout();a.iter().flat_map(|v|v.to_le_bytes()).collect()}
struct OwnedTensor{name:String,shape:Vec<usize>,bytes:Vec<u8>}impl OwnedTensor{fn one(name:impl Into<String>,a:&Array1<f32>)->Self{Self{name:name.into(),shape:vec![a.len()],bytes:bytes_1d(a)}}fn two(name:impl Into<String>,a:&Array2<f32>)->Self{Self{name:name.into(),shape:vec![a.nrows(),a.ncols()],bytes:bytes_2d(a)}}fn two_transposed(name:impl Into<String>,a:&Array2<f32>)->Self{let t=a.t().to_owned();Self::two(name,&t)}}
fn add_norm(v:&mut Vec<OwnedTensor>,p:&str,w:&Array1<f32>,b:&Array1<f32>){v.push(OwnedTensor::one(format!("{p}.weight"),w));v.push(OwnedTensor::one(format!("{p}.bias"),b));}fn add_linear(v:&mut Vec<OwnedTensor>,n:&str,w:&Array2<f32>,tr:bool){v.push(if tr{OwnedTensor::two_transposed(n,w)}else{OwnedTensor::two(n,w)});}
fn add_rwkv_block(v:&mut Vec<OwnedTensor>,model:&RwkvModel,index:usize){let b=&model.rwkv_blocks[index];let p=format!("rwkv_blocks.{index}");if let Some(n)=&b.ln0{add_norm(v,&format!("{p}.ln0"),&n.weight,&n.bias);}add_norm(v,&format!("{p}.ln1"),&b.ln1.weight,&b.ln1.bias);add_norm(v,&format!("{p}.ln2"),&b.ln2.weight,&b.ln2.bias);let t=&b.time_mix;for(n,x)in[("x_r",&t.x_r),("x_w",&t.x_w),("x_k",&t.x_k),("x_v",&t.x_v),("x_a",&t.x_a),("x_g",&t.x_g),("w0",&t.w0),("a0",&t.a0),("k_k",&t.k_k),("k_a",&t.k_a)]{v.push(OwnedTensor::one(format!("{p}.att.{n}"),x));}for(n,x)in[("w1",&t.w1),("w2",&t.w2),("a1",&t.a1),("a2",&t.a2),("g1",&t.g1),("g2",&t.g2),("r_k",&t.r_k)]{v.push(OwnedTensor::two(format!("{p}.att.{n}"),x));}if let Some(x)=&t.v1{v.push(OwnedTensor::two(format!("{p}.att.v1"),x));}if let Some(x)=&t.v2{v.push(OwnedTensor::two(format!("{p}.att.v2"),x));}if let Some(x)=&t.v0{v.push(OwnedTensor::one(format!("{p}.att.v0"),x));}add_linear(v,&format!("{p}.att.receptance.weight"),&t.receptance,true);add_linear(v,&format!("{p}.att.key.weight"),&t.key,true);add_linear(v,&format!("{p}.att.value.weight"),&t.value,true);add_linear(v,&format!("{p}.att.output.weight"),&t.output,true);add_norm(v,&format!("{p}.att.ln_x"),&t.ln_x.weight,&t.ln_x.bias);match &b.moe{Some(m)=>{v.push(OwnedTensor::two(format!("{p}.ffn.router.weight"),&m.router.weight));for(i,e)in m.experts.iter().enumerate(){v.push(OwnedTensor::one(format!("{p}.ffn.experts.{i}.x_k"),&e.x_k));add_linear(v,&format!("{p}.ffn.experts.{i}.key.weight"),&e.key,true);add_linear(v,&format!("{p}.ffn.experts.{i}.value.weight"),&e.value,true);}}None=>{v.push(OwnedTensor::one(format!("{p}.ffn.x_k"),&b.cmix.x_k));add_linear(v,&format!("{p}.ffn.key.weight"),&b.cmix.key,true);add_linear(v,&format!("{p}.ffn.value.weight"),&b.cmix.value,true);}}}
fn add_moba_block(v:&mut Vec<OwnedTensor>,model:&RwkvModel,index:usize){let b=&model.moba_blocks[index];let p=format!("moba_blocks.{index}");add_norm(v,&format!("{p}.ln1"),&b.ln1.weight,&b.ln1.bias);add_norm(v,&format!("{p}.ln2"),&b.ln2.weight,&b.ln2.bias);add_linear(v,&format!("{p}.att.receptance.weight"),&b.att.receptance.weight,false);add_linear(v,&format!("{p}.att.key.weight"),&b.att.key.weight,false);add_linear(v,&format!("{p}.att.value.weight"),&b.att.value.weight,false);add_linear(v,&format!("{p}.att.output.weight"),&b.att.output.weight,false);v.push(OwnedTensor::one(format!("{p}.ffn.x_k"),&b.ffn.x_k));add_linear(v,&format!("{p}.ffn.key.weight"),&b.ffn.key,true);add_linear(v,&format!("{p}.ffn.value.weight"),&b.ffn.value,true);}
pub fn save_model_safetensors(model:&RwkvModel,path:impl AsRef<Path>)->Result<(),String>{let mut owned=Vec::new();owned.push(OwnedTensor::two("emb.weight",&model.embedding.weight));add_norm(&mut owned,"ln_out",&model.ln_out.weight,&model.ln_out.bias);add_linear(&mut owned,"head.weight",&model.head.weight,false);for i in 0..model.rwkv_blocks.len(){add_rwkv_block(&mut owned,model,i);}for i in 0..model.moba_blocks.len(){add_moba_block(&mut owned,model,i);}let mut tensors=HashMap::with_capacity(owned.len());for t in &owned{let view=TensorView::new(Dtype::F32,t.shape.clone(),&t.bytes).map_err(|e|format!("failed to build tensor '{}': {e}",t.name))?;tensors.insert(t.name.as_str(),view);}serialize_to_file(tensors,&None,path.as_ref()).map_err(|e|format!("failed to write {}: {e}",path.as_ref().display()))}
#[cfg(test)]mod tests{use super::*;use crate::rwkv_model::{RwkvModel,RwkvModelConfig};use crate::safetensors::SafetensorsLoader;#[test]fn saved_model_contains_loader_tensors(){let model=RwkvModel::new(RwkvModelConfig::new(32,16,2,4),7);let path=std::env::temp_dir().join("smaul-native-model.safetensors");save_model_safetensors(&model,&path).unwrap();let loader=SafetensorsLoader::open(&path).unwrap();let names=loader.names().unwrap();assert!(names.contains(&"emb.weight".to_owned()));assert!(names.contains(&"ln_out.weight".to_owned()));assert!(names.contains(&"head.weight".to_owned()));assert!(names.contains(&"rwkv_blocks.0.att.key.weight".to_owned()));let _=std::fs::remove_file(path);}#[test]fn saved_moe_contains_router_and_experts(){let model=RwkvModel::new(RwkvModelConfig::new(16,8,1,4).with_moe(true,3,2),7);let path=std::env::temp_dir().join("smaul-native-moe.safetensors");save_model_safetensors(&model,&path).unwrap();let loader=SafetensorsLoader::open(&path).unwrap();let names=loader.names().unwrap();assert!(names.contains(&"rwkv_blocks.0.ffn.router.weight".to_owned()));assert!(names.contains(&"rwkv_blocks.0.ffn.experts.2.key.weight".to_owned()));let _=std::fs::remove_file(path);}}
