use ndarray::{Array1,Array2};
use crate::rwkv_model::RwkvModel;use crate::safetensors::SafetensorsLoader;
fn a1(l:&SafetensorsLoader,n:&str)->Result<Array1<f32>,String>{l.f32_1d(n)}fn a2(l:&SafetensorsLoader,n:&str)->Result<Array2<f32>,String>{l.f32_2d(n)}fn direct_linear(l:&SafetensorsLoader,n:&str)->Result<Array2<f32>,String>{l.f32_2d_transposed(n)}fn module_linear(l:&SafetensorsLoader,n:&str)->Result<Array2<f32>,String>{l.f32_2d(n)}
fn expect_shape(a:&[usize],e:&[usize],n:&str)->Result<(),String>{if a!=e{Err(format!("tensor '{n}' has shape {a:?}, expected {e:?}"))}else{Ok(())}}
fn set_norm(l:&SafetensorsLoader,p:&str,w:&mut Array1<f32>,b:&mut Array1<f32>)->Result<(),String>{let wn=format!("{p}.weight");let bn=format!("{p}.bias");let nw=a1(l,&wn)?;let nb=a1(l,&bn)?;expect_shape(nw.shape(),w.shape(),&wn)?;expect_shape(nb.shape(),b.shape(),&bn)?;*w=nw;*b=nb;Ok(())}
fn set_linear(l:&SafetensorsLoader,n:&str,t:&mut Array2<f32>,tr:bool)->Result<(),String>{let x=if tr{direct_linear(l,n)?}else{module_linear(l,n)?};expect_shape(x.shape(),t.shape(),n)?;*t=x;Ok(())}
fn load_rwkv_block(l:&SafetensorsLoader,m:&mut RwkvModel,i:usize)->Result<(),String>{let p=format!("rwkv_blocks.{i}");let b=&mut m.rwkv_blocks[i];if let Some(n)=b.ln0.as_mut(){set_norm(l,&format!("{p}.ln0"),&mut n.weight,&mut n.bias)?;}set_norm(l,&format!("{p}.ln1"),&mut b.ln1.weight,&mut b.ln1.bias)?;set_norm(l,&format!("{p}.ln2"),&mut b.ln2.weight,&mut b.ln2.bias)?;let t=&mut b.time_mix;for(n,x)in[("x_r",&mut t.x_r),("x_w",&mut t.x_w),("x_k",&mut t.x_k),("x_v",&mut t.x_v),("x_a",&mut t.x_a),("x_g",&mut t.x_g),("w0",&mut t.w0),("a0",&mut t.a0),("k_k",&mut t.k_k),("k_a",&mut t.k_a)]{let z=a1(l,&format!("{p}.att.{n}"))?;expect_shape(z.shape(),x.shape(),&format!("{p}.att.{n}"))?;*x=z;}for(n,x)in[("w1",&mut t.w1),("w2",&mut t.w2),("a1",&mut t.a1),("a2",&mut t.a2),("g1",&mut t.g1),("g2",&mut t.g2),("r_k",&mut t.r_k)]{let z=a2(l,&format!("{p}.att.{n}"))?;expect_shape(z.shape(),x.shape(),&format!("{p}.att.{n}"))?;*x=z;}for(n,x)in[("v1",&mut t.v1),("v2",&mut t.v2)]{if let Some(x)=x.as_mut(){let z=a2(l,&format!("{p}.att.{n}"))?;expect_shape(z.shape(),x.shape(),&format!("{p}.att.{n}"))?;*x=z;}}if let Some(x)=t.v0.as_mut(){let z=a1(l,&format!("{p}.att.v0"))?;expect_shape(z.shape(),x.shape(),&format!("{p}.att.v0"))?;*x=z;}set_linear(l,&format!("{p}.att.receptance.weight"),&mut t.receptance,true)?;set_linear(l,&format!("{p}.att.key.weight"),&mut t.key,true)?;set_linear(l,&format!("{p}.att.value.weight"),&mut t.value,true)?;set_linear(l,&format!("{p}.att.output.weight"),&mut t.output,true)?;set_norm(l,&format!("{p}.att.ln_x"),&mut t.ln_x.weight,&mut t.ln_x.bias)?;match &mut b.moe{Some(moe)=>{let rw=a2(l,&format!("{p}.ffn.router.weight"))?;expect_shape(rw.shape(),moe.router.weight.shape(),&format!("{p}.ffn.router.weight"))?;moe.router.weight=rw;for(i,e)in moe.experts.iter_mut().enumerate(){let x=a1(l,&format!("{p}.ffn.experts.{i}.x_k"))?;expect_shape(x.shape(),e.x_k.shape(),&format!("{p}.ffn.experts.{i}.x_k"))?;e.x_k=x;set_linear(l,&format!("{p}.ffn.experts.{i}.key.weight"),&mut e.key,true)?;set_linear(l,&format!("{p}.ffn.experts.{i}.value.weight"),&mut e.value,true)?;}}None=>{let x=a1(l,&format!("{p}.ffn.x_k"))?;expect_shape(x.shape(),b.cmix.x_k.shape(),&format!("{p}.ffn.x_k"))?;b.cmix.x_k=x;set_linear(l,&format!("{p}.ffn.key.weight"),&mut b.cmix.key,true)?;set_linear(l,&format!("{p}.ffn.value.weight"),&mut b.cmix.value,true)?;}}b.time_mix.refresh_quantized();Ok(())}
fn load_moba_block(l:&SafetensorsLoader,m:&mut RwkvModel,i:usize)->Result<(),String>{let p=format!("moba_blocks.{i}");let b=&mut m.moba_blocks[i];set_norm(l,&format!("{p}.ln1"),&mut b.ln1.weight,&mut b.ln1.bias)?;set_norm(l,&format!("{p}.ln2"),&mut b.ln2.weight,&mut b.ln2.bias)?;for(n,x)in[("receptance.weight",&mut b.att.receptance.weight),("key.weight",&mut b.att.key.weight),("value.weight",&mut b.att.value.weight),("output.weight",&mut b.att.output.weight)]{set_linear(l,&format!("{p}.att.{n}"),x,false)?;}let x=a1(l,&format!("{p}.ffn.x_k"))?;expect_shape(x.shape(),b.ffn.x_k.shape(),&format!("{p}.ffn.x_k"))?;b.ffn.x_k=x;set_linear(l,&format!("{p}.ffn.key.weight"),&mut b.ffn.key,true)?;set_linear(l,&format!("{p}.ffn.value.weight"),&mut b.ffn.value,true)?;Ok(())}
pub fn load_model_safetensors(model:&mut RwkvModel,path:impl AsRef<std::path::Path>)->Result<(),String>{let l=SafetensorsLoader::open(path)?;let e=l.f32_2d("emb.weight")?;expect_shape(e.shape(),model.embedding.weight.shape(),"emb.weight")?;model.embedding.weight=e;set_norm(&l,"ln_out",&mut model.ln_out.weight,&mut model.ln_out.bias)?;set_linear(&l,"head.weight",&mut model.head.weight,false)?;for i in 0..model.rwkv_blocks.len(){load_rwkv_block(&l,model,i)?;}for i in 0..model.moba_blocks.len(){load_moba_block(&l,model,i)?;}Ok(())}
#[cfg(test)]mod tests{use super::*;use crate::rwkv_model::RwkvModelConfig;use std::path::Path;#[test]fn loader_rejects_missing_checkpoint(){let mut model=RwkvModel::new(RwkvModelConfig::new(32,16,2,4),1);assert!(load_model_safetensors(&mut model,Path::new("/definitely/missing/model.safetensors")).is_err());}#[test]fn shape_guard_rejects_wrong_dimensions(){assert!(expect_shape(&[4,5],&[4,6],"test").is_err());assert!(expect_shape(&[4,5],&[4,5],"test").is_ok());}}
