use crate::inference::sample;
use crate::model_io::PretrainedModel;
use crate::model_train_step::ModelTrainStep;
use crate::training::TrainStep;
use ndarray::Array2;
use rand::{Rng,SeedableRng};
use serde::{Deserialize,Serialize};
use std::fs::{self,OpenOptions};
use std::io::Write;
use std::path::{Path,PathBuf};

#[derive(Clone,Debug,Serialize,Deserialize)]
pub struct Candidate{pub id:usize,pub text:String,pub tokens:Vec<usize>,pub old_logprobs:Vec<f32>}
#[derive(Clone,Debug,Serialize,Deserialize)]
pub struct Preference{pub prompt:String,pub responses:Vec<String>,pub chosen:usize,pub source:String}

pub struct SmaulRl{pub model:PretrainedModel,pub work_dir:PathBuf,pub eos_id:usize}
impl SmaulRl{
 pub fn load(model_dir:impl AsRef<Path>,work_dir:impl AsRef<Path>)->Result<Self,String>{let model=PretrainedModel::load(model_dir)?;let work_dir=work_dir.as_ref().to_path_buf();fs::create_dir_all(&work_dir).map_err(|e|e.to_string())?;let eos_id=model.tokenizer.eos_id();Ok(Self{model,work_dir,eos_id})}
 pub fn generate(&self,prompt:&str,max_new:usize,temp:f32,top_k:usize,top_p:f32,seed:u64)->Candidate{let mut ids=self.model.tokenizer.encode(prompt);if ids.is_empty(){ids.push(self.model.tokenizer.bos_id());}let mut rng=rand::rngs::StdRng::seed_from_u64(seed);let(mut logits,mut state)=self.model.model.forward(&ids,None);let mut response=Vec::new();let mut old=Vec::new();for _ in 0..max_new{let row=logits.row(logits.nrows()-1);let values=row.as_slice().unwrap();let token=sample(values,temp,top_k,top_p,1.0,&response,&mut rng);if token==self.eos_id{break;}old.push(logprob(values,token,temp));response.push(token);(logits,state)=self.model.model.forward(&[token],Some(&state));}Candidate{id:0,text:self.model.tokenizer.decode(&response),tokens:response,old_logprobs:old}}
 pub fn candidates(&self,prompt:&str,count:usize,max_new:usize,temp:f32,top_k:usize,top_p:f32)->Vec<Candidate>{let mut rng=rand::rng();(0..count).map(|id|{let mut c=self.generate(prompt,max_new,temp,top_k,top_p,rng.random());c.id=id;c}).collect()}
 pub fn save_preference(&self,prompt:&str,candidates:&[Candidate],chosen:usize,source:&str)->Result<(),String>{if chosen>=candidates.len(){return Err("chosen response is out of range".into())}let r=Preference{prompt:prompt.into(),responses:candidates.iter().map(|x|x.text.clone()).collect(),chosen,source:source.into()};let path=self.work_dir.join("preferences.jsonl");let mut f=OpenOptions::new().create(true).append(true).open(path).map_err(|e|e.to_string())?;writeln!(f,"{}",serde_json::to_string(&r).map_err(|e|e.to_string())?).map_err(|e|e.to_string())}
 pub fn grpo_loss(candidates:&[Candidate],chosen:usize,clip:f32,kl_coef:f32)->f32{assert!(chosen<candidates.len());let adv=advantages(candidates.len(),chosen);let mut total=0.0;let mut count=0usize;for(i,c)in candidates.iter().enumerate(){for&old in &c.old_logprobs{let ratio=1.0f32;let clipped=ratio.clamp(1.0-clip,1.0+clip);total+=-(ratio*adv[i]).min(clipped*adv[i])+kl_coef*(old-old);count+=1;}}total/count.max(1)as f32}
 pub fn grpo_update(&mut self,prompt:&str,candidates:&[Candidate],chosen:usize,clip:f32,kl_coef:f32,lr:f32)->Result<f32,String>{if candidates.is_empty(){return Err("GRPO requires at least one candidate".into())}if chosen>=candidates.len(){return Err("chosen response is out of range".into())}let prompt_ids=self.model.tokenizer.encode(prompt);if prompt_ids.is_empty(){return Err("prompt tokenization produced no tokens".into())}let adv=advantages(candidates.len(),chosen);let mut train=TrainStep::new(&self.model.model,lr);let mut total_loss=0.0;let mut total_tokens=0usize;for(i,c)in candidates.iter().enumerate(){if c.tokens.is_empty(){continue}if c.old_logprobs.len()!=c.tokens.len(){return Err(format!("candidate {} has mismatched token/logprob lengths",c.id))}let mut input=prompt_ids.clone();if c.tokens.len()>1{input.extend_from_slice(&c.tokens[..c.tokens.len()-1]);}let(logits,tape,next_state)=self.model.model.forward_with_tape_and_state(&input,None);let mut grad=Array2::zeros(logits.dim());let mut loss=0.0;for j in 0..c.tokens.len(){let row=prompt_ids.len()-1+j;let values=logits.row(row);let token=c.tokens[j];let new_lp=logprob(values.as_slice().unwrap(),token,1.0);let old_lp=c.old_logprobs[j];let ratio=(new_lp-old_lp).exp().clamp(0.0,1e6);let a=adv[i];let unclipped=ratio*a;let clipped=ratio.clamp(1.0-clip,1.0+clip)*a;let active=unclipped<=clipped;let policy_coeff=if active{ratio*a}else{0.0};let p=softmax(values.as_slice().unwrap());for v in 0..p.len(){let one=if v==token{1.0}else{0.0};grad[[row,v]]+=(-policy_coeff+kl_coef)*(one-p[v]);}loss+=-unclipped.min(clipped)+kl_coef*(new_lp-old_lp);}let step=ModelTrainStep::from_logits_gradient(&self.model.model,&input,logits,tape,next_state,loss,grad);train.step(&mut self.model.model,&step.gradients);total_loss+=loss;total_tokens+=c.tokens.len();}if total_tokens==0{return Ok(0.0)}Ok(total_loss/total_tokens as f32)}
 pub fn train_response(&mut self,tokens:&[usize],lr:f32)->Result<f32,String>{if tokens.len()<2{return Ok(0.0)}let targets=ndarray::Array1::from_vec(tokens[1..].to_vec());let input=&tokens[..tokens.len()-1];let step=ModelTrainStep::run(&self.model.model,input,&targets);let loss=step.loss;let mut train=TrainStep::new(&self.model.model,lr);train.step(&mut self.model.model,&step.gradients);Ok(loss)}
 pub fn run_human(&mut self,prompts:&[String],count:usize,max_new:usize,temp:f32,top_k:usize,top_p:f32,lr:f32)->Result<(),String>{if count<2{return Err("responses must be at least 2".into())}for prompt in prompts{let c=self.candidates(prompt,count,max_new,temp,top_k,top_p);for(x,i)in c.iter().enumerate(){println!("\n[{}]\n{}",x+1,i.text)}let chosen=loop{print!("Choose best response [1-{}]: ",count);std::io::stdout().flush().ok();let mut s=String::new();std::io::stdin().read_line(&mut s).map_err(|e|e.to_string())?;if let Ok(n)=s.trim().parse::<usize>(){if (1..=count).contains(&n){break n-1}}println!("Invalid choice.")};self.save_preference(prompt,&c,chosen,"human")?;let loss=self.grpo_update(prompt,&c,chosen,0.2,0.01,lr)?;println!("[GRPO] loss={loss:.5}");}Ok(())}
}
fn softmax(values:&[f32])->Vec<f32>{let m=values.iter().copied().fold(f32::NEG_INFINITY,f32::max);let mut p=values.iter().map(|v|(v-m).exp()).collect::<Vec<_>>();let z=p.iter().sum::<f32>().max(1e-20);for v in &mut p{*v/=z;}p}
fn logprob(values:&[f32],token:usize,temp:f32)->f32{assert!(token<values.len());let t=temp.max(1e-8);let m=values.iter().map(|v|*v/t).fold(f32::NEG_INFINITY,f32::max);let z=values.iter().map(|v|(*v/t-m).exp()).sum::<f32>().max(1e-20);values[token]/t-m-z.ln()}
fn advantages(n:usize,chosen:usize)->Vec<f32>{if n==0{return Vec::new()}let mut r=vec![-1.0;n];r[chosen]=1.0;let mean=r.iter().sum::<f32>()/n as f32;let std=(r.iter().map(|x|(x-mean).powi(2)).sum::<f32>()/n as f32).sqrt().max(1e-6);r.into_iter().map(|x|(x-mean)/std).collect()}
