use crate::inference::sample;
use crate::model_io::PretrainedModel;
use crate::model_train_step::ModelTrainStep;
use crate::model_gradients::ModelGradients;
use crate::training::TrainStep;
use ndarray::Array2;
use rand::{Rng,SeedableRng};
use serde::{Deserialize,Serialize};
use std::fs::{self,OpenOptions};
use std::io::Write;
use std::path::{Path,PathBuf};

#[derive(Clone,Debug,Serialize,Deserialize)]
pub struct Candidate{pub id:usize,pub text:String,pub tokens:Vec<usize>,pub old_logprobs:Vec<f32>,pub temperature:f32,pub top_k:usize,pub top_p:f32}
#[derive(Clone,Debug,Serialize,Deserialize)]
pub struct Preference{pub prompt:String,pub responses:Vec<String>,pub chosen:usize,pub source:String}
pub struct SmaulRl{pub model:PretrainedModel,pub work_dir:PathBuf,pub eos_id:usize}
impl SmaulRl{
 pub fn load(model_dir:impl AsRef<Path>,work_dir:impl AsRef<Path>)->Result<Self,String>{let model=PretrainedModel::load(model_dir)?;let work_dir=work_dir.as_ref().to_path_buf();fs::create_dir_all(&work_dir).map_err(|e|e.to_string())?;let eos_id=model.tokenizer.eos_id();Ok(Self{model,work_dir,eos_id})}
 pub fn generate(&self,prompt:&str,max_new:usize,temp:f32,top_k:usize,top_p:f32,seed:u64)->Candidate{let mut ids=self.model.tokenizer.encode(prompt);if ids.is_empty(){ids.push(self.model.tokenizer.bos_id());}let mut rng=rand::rngs::StdRng::seed_from_u64(seed);let(mut logits,mut state)=self.model.model.forward(&ids,None);let mut response=Vec::new();let mut old=Vec::new();for _ in 0..max_new{let values=logits.row(logits.nrows()-1).to_vec();let(token,lp)=sample_filtered(&values,temp,top_k,top_p,&mut rng);if token==self.eos_id{break;}old.push(lp);response.push(token);(logits,state)=self.model.model.forward(&[token],Some(&state));}Candidate{id:0,text:self.model.tokenizer.decode(&response),tokens:response,old_logprobs:old,temperature:temp,top_k,top_p}}
 pub fn candidates(&self,prompt:&str,count:usize,max_new:usize,temp:f32,top_k:usize,top_p:f32)->Vec<Candidate>{let mut rng=rand::rng();(0..count).map(|id|{let mut c=self.generate(prompt,count.max(max_new).min(max_new),temp,top_k,top_p,rng.random());c.id=id;c}).collect()}
 pub fn save_preference(&self,prompt:&str,candidates:&[Candidate],chosen:usize,source:&str)->Result<(),String>{if chosen>=candidates.len(){return Err("chosen response is out of range".into())}let r=Preference{prompt:prompt.into(),responses:candidates.iter().map(|x|x.text.clone()).collect(),chosen,source:source.into()};let path=self.work_dir.join("preferences.jsonl");let mut f=OpenOptions::new().create(true).append(true).open(path).map_err(|e|e.to_string())?;writeln!(f,"{}",serde_json::to_string(&r).map_err(|e|e.to_string())?).map_err(|e|e.to_string())}
 pub fn grpo_loss(candidates:&[Candidate],chosen:usize,clip:f32,_kl_coef:f32)->f32{assert!(chosen<candidates.len());let adv=advantages(candidates.len(),chosen);let mut total=0.0;let mut count=0usize;for(i,c)in candidates.iter().enumerate(){for _ in &c.tokens{let ratio=1.0f32;let clipped=ratio.clamp(1.0-clip,1.0+clip);total+=-(ratio*adv[i]).min(clipped*adv[i]);count+=1;}}total/count.max(1)as f32}
 pub fn grpo_update(&mut self,prompt:&str,candidates:&[Candidate],chosen:usize,clip:f32,kl_coef:f32,lr:f32)->Result<f32,String>{if candidates.is_empty(){return Err("GRPO requires at least one candidate".into())}if chosen>=candidates.len(){return Err("chosen response is out of range".into())}let prompt_ids=self.model.tokenizer.encode(prompt);let prompt_ids=if prompt_ids.is_empty(){vec![self.model.tokenizer.bos_id()]}else{prompt_ids};let adv=advantages(candidates.len(),chosen);let mut accumulated:Option<ModelGradients>=None;let mut losses=Vec::new();for(i,c)in candidates.iter().enumerate(){if c.tokens.is_empty(){continue}if c.old_logprobs.len()!=c.tokens.len(){return Err(format!("candidate {} has mismatched policy snapshot lengths",c.id))}let mut input=prompt_ids.clone();input.extend_from_slice(&c.tokens);let(logits,tape,next_state)=self.model.model.forward_with_tape_and_state(&input,None);let start=prompt_ids.len()-1;let mut grad=Array2::zeros(logits.dim());let mut loss=0.0;for j in 0..c.tokens.len(){let row=start+j;let values=logits.row(row).to_vec();let(_,new_lp)=sample_logprob(&values,c.tokens[j],c.temperature,c.top_k,c.top_p);let old_lp=c.old_logprobs[j];let log_ratio=new_lp-old_lp;let ratio=log_ratio.clamp(-20.0,20.0).exp();let clipped=ratio.clamp(1.0-clip,1.0+clip);let a=adv[i];let min_obj=(ratio*a).min(clipped*a);let active=(a>=0.0&&ratio<=1.0+clip)||(a<0.0&&ratio>=1.0-clip);let policy_coeff=if active{ratio*a}else{0.0};let p=filtered_probs(&values,c.temperature,c.top_k,c.top_p);for v in 0..p.len(){let one=if v==c.tokens[j]{1.0}else{0.0};grad[[row,v]]+=-policy_coeff*(one-p[v]);}loss+=-min_obj-kl_coef*log_ratio;}let step=ModelTrainStep::from_logits_gradient(&self.model.model,&input,logits,tape,next_state,loss,grad);if let Some(g)=&mut accumulated{g.add_in_place(&step.gradients)}else{accumulated=Some(step.gradients)}losses.push(loss);}if let Some(g)=accumulated{let train=TrainStep::new(&self.model.model,lr);train.step_sgd(&mut self.model.model,&g,lr);}Ok(if losses.is_empty(){0.0}else{losses.iter().sum::<f32>()/losses.len() as f32})}
 pub fn train_response(&mut self,tokens:&[usize],lr:f32)->Result<f32,String>{if tokens.len()<2{return Ok(0.0)}let targets=ndarray::Array1::from_vec(tokens[1..].to_vec());let input=&tokens[..tokens.len()-1];let step=ModelTrainStep::run(&self.model.model,input,&targets);let mut train=TrainStep::new(&self.model.model,lr);train.step(&mut self.model.model,&step.gradients);Ok(step.loss)}
 pub fn run_human(&mut self,prompts:&[String],count:usize,max_new:usize,temp:f32,top_k:usize,top_p:f32,lr:f32)->Result<(),String>{if count<2{return Err("responses must be at least 2".into())}for prompt in prompts{let c=self.candidates(prompt,count,max_new,temp,top_k,top_p);for(x,i)in c.iter().enumerate(){println!("\n[{}]\n{}",x+1,i.text)}let chosen=loop{print!("Choose best response [1-{}]: ",count);std::io::stdout().flush().ok();let mut s=String::new();std::io::stdin().read_line(&mut s).map_err(|e|e.to_string())?;if let Ok(n)=s.trim().parse::<usize>(){if (1..=count).contains(&n){break n-1}}println!("Invalid choice.")};self.save_preference(prompt,&c,chosen,"human")?;let loss=self.grpo_update(prompt,&c,chosen,0.2,0.01,lr)?;println!("[GRPO] loss={loss:.5}");}Ok(())}
}
fn filtered_probs(values:&[f32],temperature:f32,top_k:usize,top_p:f32)->Vec<f32>{let logits=filtered_logits(values,temperature,top_k,top_p);let m=logits.iter().copied().fold(f32::NEG_INFINITY,f32::max);let mut p=logits.iter().map(|x|if x.is_finite(){(*x-m).exp()}else{0.0}).collect::<Vec<_>>();let z=p.iter().sum::<f32>().max(1e-20);for x in &mut p{*x/=z;}p}
fn filtered_logits(values:&[f32],temperature:f32,top_k:usize,top_p:f32)->Vec<f32>{assert!(temperature>0.0,"temperature must be > 0 for policy sampling");let mut logits=values.iter().map(|v|*v/temperature).collect::<Vec<_>>();if top_k>0&&top_k<logits.len(){let mut sorted=logits.clone();sorted.sort_by(|a,b|b.partial_cmp(a).unwrap());let cutoff=sorted[top_k-1];for x in &mut logits{if *x<cutoff{*x=f32::NEG_INFINITY;}}}if top_p>0.0&&top_p<1.0{let mut order=(0..logits.len()).collect::<Vec<_>>();order.sort_by(|&a,&b|logits[b].partial_cmp(&logits[a]).unwrap());let m=logits.iter().copied().fold(f32::NEG_INFINITY,f32::max);let z=logits.iter().map(|x|if x.is_finite(){(*x-m).exp()}else{0.0}).sum::<f32>().max(1e-20);let mut cumulative=0.0;let mut remove=vec![false;logits.len()];for(pos,&idx)in order.iter().enumerate(){let p=if logits[idx].is_finite(){(logits[idx]-m).exp()/z}else{0.0};if cumulative+p>top_p&&pos>0{remove[idx]=true;}cumulative+=p;}for i in 0..logits.len(){if remove[i]{logits[i]=f32::NEG_INFINITY;}}}logits}
fn sample_logprob(values:&[f32],token:usize,temp:f32,top_k:usize,top_p:f32)->(Vec<f32>,f32){let p=filtered_probs(values,temp,top_k,top_p);assert!(token<p.len());(p.clone(),p[token].max(1e-20).ln())}
fn sample_filtered(values:&[f32],temp:f32,top_k:usize,top_p:f32,rng:&mut impl Rng)->(usize,f32){let p=filtered_probs(values,temp,top_k,top_p);let mut r=rng.random::<f32>();for(i,x)in p.iter().enumerate(){if r<*x{return(i,x.max(1e-20).ln())}r-=*x;}(p.len()-1,p[p.len()-1].max(1e-20).ln())}
fn advantages(n:usize,chosen:usize)->Vec<f32>{if n==0{return Vec::new()}let mut r=vec![-1.0;n];r[chosen]=1.0;let mean=r.iter().sum::<f32>()/n as f32;let std=(r.iter().map(|x|(x-mean).powi(2)).sum::<f32>()/n as f32).sqrt().max(1e-6);r.into_iter().map(|x|(x-mean)/std).collect()}
