use ndarray::{Array1,Array2,Array4};
use crate::layer_norm_backward;
use crate::moe_backward::{self,MoeBackward};
use crate::rwkv_block::RwkvBlock;
use crate::rwkv_block_full_tape::RwkvBlockFullTape;
use crate::rwkv_cmix_backward::{self,CmixBackward};
use crate::rwkv_time_mix_backward_full;
pub struct RwkvBlockBackward{pub grad_input:Array2<f32>,pub grad_time_prev:Array1<f32>,pub grad_cmix_prev:Array1<f32>,pub grad_time_state:Array4<f32>,pub grad_v_first:Array2<f32>,pub grad_ln0_weight:Option<Array1<f32>>,pub grad_ln0_bias:Option<Array1<f32>>,pub grad_ln1_weight:Array1<f32>,pub grad_ln1_bias:Array1<f32>,pub grad_ln2_weight:Array1<f32>,pub grad_ln2_bias:Array1<f32>,pub time:rwkv_time_mix_backward_full::RwkvTimeMixBackward,pub cmix:Option<CmixBackward>,pub moe:Option<MoeBackward>}
pub fn backward(block:&RwkvBlock,tape:&RwkvBlockFullTape,go:&Array2<f32>,gns:Option<&Array4<f32>>,gnt:Option<&Array1<f32>>,gnc:Option<&Array1<f32>>,gnv:Option<&Array2<f32>>)->RwkvBlockBackward{let prev=tape.initial_state.as_ref().map(|s|&s.cmix_prev);let(gi,gp,cm,m)=match&block.moe{Some(x)=>{let mut r=moe_backward::backward(x,&tape.cmix_input,prev,go);if let Some(g)=gnc{r.grad_prev+=g}(r.grad_input.clone(),r.grad_prev.clone(),None,Some(r))}None=>{let(k,v)=block.cmix.effective_weights();let mut r=rwkv_cmix_backward::backward(&tape.cmix_input,prev,go,&block.cmix.x_k,&k,&v);if let Some(g)=gnc{r.grad_prev+=g}(r.grad_input.clone(),r.grad_prev.clone(),Some(r),None)}};let(l2i,l2w,l2b)=layer_norm_backward::backward(&tape.ln2_input,&gi,&block.ln2.weight,block.ln2.eps);let gr=go+&l2i;let mut time=rwkv_time_mix_backward_full::backward(&block.time_mix,&tape.time,&gr);if let Some(g)=gns{time.grad_state+=g}if let Some(g)=gnt{time.grad_prev+=g}if let Some(g)=gnv{time.grad_v_first+=g}let(l1i,l1w,l1b)=layer_norm_backward::backward(&tape.ln1_input,&time.grad_input,&block.ln1.weight,block.ln1.eps);let into=gr+&l1i;let(mut l0w,mut l0b)=(None,None);let input=if let(Some(n),Some(i))=(block.ln0.as_ref(),tape.ln0_input.as_ref()){let(d,w,b)=layer_norm_backward::backward(i,&into,&n.weight,n.eps);l0w=Some(w);l0b=Some(b);d}else{into};RwkvBlockBackward{grad_input:input,grad_time_prev:time.grad_prev.clone(),grad_cmix_prev:gp,grad_time_state:time.grad_state.clone(),grad_v_first:time.grad_v_first.clone(),grad_ln0_weight:l0w,grad_ln0_bias:l0b,grad_ln1_weight:l1w,grad_ln1_bias:l1b,grad_ln2_weight:l2w,grad_ln2_bias:l2b,time,cmix:cm,moe:m}}
#[cfg(test)]mod tests{use super::*;#[test]fn qat_backward_uses_effective_weights(){let b=RwkvBlock::new_with_moe_and_qat(8,2,0,4,false,1,1,1,8);let x=Array2::ones((2,8));let(_,_,t)=b.forward_with_full_tape(&x,None,None);let r=backward(&b,&t,&Array2::ones((2,8)),None,None,None,None);assert!(r.grad_input.iter().all(|v|v.is_finite()));}}
