use ndarray::{Array1, Array2};
use crate::gradient::clip_by_global_norm;
use crate::model_gradients::{LayerGradients, ModelGradients, MobaLayerGradients};
use crate::loss::cross_entropy;
use crate::optimizer::{Lion, Optimizer};
use crate::rwkv_model::RwkvModel;

pub struct TrainStep { pub optimizer: Lion, pub max_grad_norm: Option<f32> }
impl TrainStep {
 pub fn new(model:&RwkvModel,lr:f32)->Self{Self{optimizer:Lion::new(model.parameter_count(),lr,0.9,0.99,0.0),max_grad_norm:Some(1.0)}}
 pub fn loss_and_gradient(logits:&Array2<f32>,targets:&Array1<usize>)->(f32,Array2<f32>){cross_entropy(logits,targets)}
 pub fn clip_logits_gradient(&self,grad:&mut Array2<f32>)->f32{let mut refs=vec![grad];match self.max_grad_norm{Some(max_norm)=>clip_by_global_norm(&mut refs,max_norm),None=>clip_by_global_norm(&mut refs,f32::MAX)}}
 pub fn token_count(model:&RwkvModel)->usize{model.config.vocab_size}
 pub fn step(&mut self,model:&mut RwkvModel,gradients:&ModelGradients)->f32{assert_eq!(gradients.layers.len(),model.rwkv_blocks.len());assert_eq!(gradients.moba_layers.len(),model.moba_blocks.len());assert_eq!(gradients.parameter_count(),model.parameter_count());let mut parameters=Vec::with_capacity(model.parameter_count());let mut grads=Vec::with_capacity(model.parameter_count());collect_model(model,gradients,&mut parameters,&mut grads);let norm=global_norm(&grads);let scale=self.max_grad_norm.map(|max|if norm>max{max/norm}else{1.0}).unwrap_or(1.0);if scale!=1.0{for g in &mut grads{*g*=scale;}}self.optimizer.step(&mut parameters,&grads);write_model(model,&parameters);norm}
}
fn global_norm(values:&[f32])->f32{values.iter().map(|v|v*v).sum::<f32>().sqrt()}
fn push(a:&mut Vec<f32>,g:&mut Vec<f32>,p:&[f32],d:&[f32]){assert_eq!(p.len(),d.len());a.extend_from_slice(p);g.extend_from_slice(d);}
fn collect_layer(layer:&crate::rwkv_block::RwkvBlock,grad:&LayerGradients,p:&mut Vec<f32>,g:&mut Vec<f32>){if let(Some(n),Some(w),Some(b))=(&layer.ln0,&grad.ln0_weight,&grad.ln0_bias){push(p,g,n.weight.as_slice().unwrap(),w.as_slice().unwrap());push(p,g,n.bias.as_slice().unwrap(),b.as_slice().unwrap());}push(p,g,layer.ln1.weight.as_slice().unwrap(),grad.ln1_weight.as_slice().unwrap());push(p,g,layer.ln1.bias.as_slice().unwrap(),grad.ln1_bias.as_slice().unwrap());push(p,g,layer.ln2.weight.as_slice().unwrap(),grad.ln2_weight.as_slice().unwrap());push(p,g,layer.ln2.bias.as_slice().unwrap(),grad.ln2_bias.as_slice().unwrap());let t=&layer.time_mix;push(p,g,t.x_r.as_slice().unwrap(),grad.time_x_r.as_slice().unwrap());push(p,g,t.x_w.as_slice().unwrap(),grad.time_x_w.as_slice().unwrap());push(p,g,t.x_k.as_slice().unwrap(),grad.time_x_k.as_slice().unwrap());push(p,g,t.x_v.as_slice().unwrap(),grad.time_x_v.as_slice().unwrap());push(p,g,t.x_a.as_slice().unwrap(),grad.time_x_a.as_slice().unwrap());push(p,g,t.x_g.as_slice().unwrap(),grad.time_x_g.as_slice().unwrap());push(p,g,t.w0.as_slice().unwrap(),grad.time_w0.as_slice().unwrap());push(p,g,t.w1.as_slice().unwrap(),grad.time_w1.as_slice().unwrap());push(p,g,t.w2.as_slice().unwrap(),grad.time_w2.as_slice().unwrap());push(p,g,t.a0.as_slice().unwrap(),grad.time_a0.as_slice().unwrap());push(p,g,t.a1.as_slice().unwrap(),grad.time_a1.as_slice().unwrap());push(p,g,t.a2.as_slice().unwrap(),grad.time_a2.as_slice().unwrap());if let(Some(x),Some(d))=(&t.v0,&grad.time_v0){push(p,g,x.as_slice().unwrap(),d.as_slice().unwrap());}if let(Some(x),Some(d))=(&t.v1,&grad.time_v1){push(p,g,x.as_slice().unwrap(),d.as_slice().unwrap());}if let(Some(x),Some(d))=(&t.v2,&grad.time_v2){push(p,g,x.as_slice().unwrap(),d.as_slice().unwrap());}push(p,g,t.g1.as_slice().unwrap(),grad.time_g1.as_slice().unwrap());push(p,g,t.g2.as_slice().unwrap(),grad.time_g2.as_slice().unwrap());push(p,g,t.k_k.as_slice().unwrap(),grad.time_k_k.as_slice().unwrap());push(p,g,t.k_a.as_slice().unwrap(),grad.time_k_a.as_slice().unwrap());push(p,g,t.r_k.as_slice().unwrap(),grad.time_r_k.as_slice().unwrap());push(p,g,t.receptance.as_slice().unwrap(),grad.time_receptance.as_slice().unwrap());push(p,g,t.key.as_slice().unwrap(),grad.time_key.as_slice().unwrap());push(p,g,t.value.as_slice().unwrap(),grad.time_value.as_slice().unwrap());push(p,g,t.output.as_slice().unwrap(),grad.time_output.as_slice().unwrap());push(p,g,t.ln_x.weight.as_slice().unwrap(),grad.time_ln_weight.as_slice().unwrap());push(p,g,t.ln_x.bias.as_slice().unwrap(),grad.time_ln_bias.as_slice().unwrap());push(p,g,layer.cmix.x_k.as_slice().unwrap(),grad.cmix_x_k.as_slice().unwrap());push(p,g,layer.cmix.key.as_slice().unwrap(),grad.cmix_key.as_slice().unwrap());push(p,g,layer.cmix.value.as_slice().unwrap(),grad.cmix_value.as_slice().unwrap());}
fn collect_moba(layer:&crate::moba_block::MobaBlock,grad:&MobaLayerGradients,p:&mut Vec<f32>,g:&mut Vec<f32>){push(p,g,layer.ln1.weight.as_slice().unwrap(),grad.ln1_weight.as_slice().unwrap());push(p,g,layer.ln1.bias.as_slice().unwrap(),grad.ln1_bias.as_slice().unwrap());push(p,g,layer.ln2.weight.as_slice().unwrap(),grad.ln2_weight.as_slice().unwrap());push(p,g,layer.ln2.bias.as_slice().unwrap(),grad.ln2_bias.as_slice().unwrap());push(p,g,layer.att.receptance.weight.as_slice().unwrap(),grad.receptance.as_slice().unwrap());push(p,g,layer.att.key.weight.as_slice().unwrap(),grad.key.as_slice().unwrap());push(p,g,layer.att.value.weight.as_slice().unwrap(),grad.value.as_slice().unwrap());push(p,g,layer.att.output.weight.as_slice().unwrap(),grad.output.as_slice().unwrap());push(p,g,layer.ffn.x_k.as_slice().unwrap(),grad.cmix_x_k.as_slice().unwrap());push(p,g,layer.ffn.key.as_slice().unwrap(),grad.cmix_key.as_slice().unwrap());push(p,g,layer.ffn.value.as_slice().unwrap(),grad.cmix_value.as_slice().unwrap());}
fn collect_model(model:&RwkvModel,gradients:&ModelGradients,p:&mut Vec<f32>,g:&mut Vec<f32>){push(p,g,model.embedding.weight.as_slice().unwrap(),gradients.embedding.as_slice().unwrap());for(layer,grad)in model.rwkv_blocks.iter().zip(&gradients.layers){collect_layer(layer,grad,p,g);}for(layer,grad)in model.moba_blocks.iter().zip(&gradients.moba_layers){collect_moba(layer,grad,p,g);}push(p,g,model.ln_out.weight.as_slice().unwrap(),gradients.ln_out_weight.as_slice().unwrap());push(p,g,model.ln_out.bias.as_slice().unwrap(),gradients.ln_out_bias.as_slice().unwrap());push(p,g,model.head.weight.as_slice().unwrap(),gradients.head.as_slice().unwrap());}
fn write_slice(dst:&mut[f32],src:&[f32],offset:&mut usize){let end=*offset+dst.len();dst.copy_from_slice(&src[*offset..end]);*offset=end;}
fn write_layer(layer:&mut crate::rwkv_block::RwkvBlock,src:&[f32],o:&mut usize){if let Some(n)=&mut layer.ln0{write_slice(n.weight.as_slice_mut().unwrap(),src,o);write_slice(n.bias.as_slice_mut().unwrap(),src,o);}write_slice(layer.ln1.weight.as_slice_mut().unwrap(),src,o);write_slice(layer.ln1.bias.as_slice_mut().unwrap(),src,o);write_slice(layer.ln2.weight.as_slice_mut().unwrap(),src,o);write_slice(layer.ln2.bias.as_slice_mut().unwrap(),src,o);let t=&mut layer.time_mix;write_slice(t.x_r.as_slice_mut().unwrap(),src,o);write_slice(t.x_w.as_slice_mut().unwrap(),src,o);write_slice(t.x_k.as_slice_mut().unwrap(),src,o);write_slice(t.x_v.as_slice_mut().unwrap(),src,o);write_slice(t.x_a.as_slice_mut().unwrap(),src,o);write_slice(t.x_g.as_slice_mut().unwrap(),src,o);write_slice(t.w0.as_slice_mut().unwrap(),src,o);write_slice(t.w1.as_slice_mut().unwrap(),src,o);write_slice(t.w2.as_slice_mut().unwrap(),src,o);write_slice(t.a0.as_slice_mut().unwrap(),src,o);write_slice(t.a1.as_slice_mut().unwrap(),src,o);write_slice(t.a2.as_slice_mut().unwrap(),src,o);if let Some(x)=&mut t.v0{write_slice(x.as_slice_mut().unwrap(),src,o);}if let Some(x)=&mut t.v1{write_slice(x.as_slice_mut().unwrap(),src,o);}if let Some(x)=&mut t.v2{write_slice(x.as_slice_mut().unwrap(),src,o);}write_slice(t.g1.as_slice_mut().unwrap(),src,o);write_slice(t.g2.as_slice_mut().unwrap(),src,o);write_slice(t.k_k.as_slice_mut().unwrap(),src,o);write_slice(t.k_a.as_slice_mut().unwrap(),src,o);write_slice(t.r_k.as_slice_mut().unwrap(),src,o);write_slice(t.receptance.as_slice_mut().unwrap(),src,o);write_slice(t.key.as_slice_mut().unwrap(),src,o);write_slice(t.value.as_slice_mut().unwrap(),src,o);write_slice(t.output.as_slice_mut().unwrap(),src,o);write_slice(t.ln_x.weight.as_slice_mut().unwrap(),src,o);write_slice(t.ln_x.bias.as_slice_mut().unwrap(),src,o);write_slice(layer.cmix.x_k.as_slice_mut().unwrap(),src,o);write_slice(layer.cmix.key.as_slice_mut().unwrap(),src,o);write_slice(layer.cmix.value.as_slice_mut().unwrap(),src,o);}
fn write_moba(layer:&mut crate::moba_block::MobaBlock,src:&[f32],o:&mut usize){write_slice(layer.ln1.weight.as_slice_mut().unwrap(),src,o);write_slice(layer.ln1.bias.as_slice_mut().unwrap(),src,o);write_slice(layer.ln2.weight.as_slice_mut().unwrap(),src,o);write_slice(layer.ln2.bias.as_slice_mut().unwrap(),src,o);write_slice(layer.att.receptance.weight.as_slice_mut().unwrap(),src,o);write_slice(layer.att.key.weight.as_slice_mut().unwrap(),src,o);write_slice(layer.att.value.weight.as_slice_mut().unwrap(),src,o);write_slice(layer.att.output.weight.as_slice_mut().unwrap(),src,o);write_slice(layer.ffn.x_k.as_slice_mut().unwrap(),src,o);write_slice(layer.ffn.key.as_slice_mut().unwrap(),src,o);write_slice(layer.ffn.value.as_slice_mut().unwrap(),src,o);}
fn write_model(model:&mut RwkvModel,src:&[f32]){let mut o=0;write_slice(model.embedding.weight.as_slice_mut().unwrap(),src,&mut o);for layer in &mut model.rwkv_blocks{write_layer(layer,src,&mut o);}for layer in &mut model.moba_blocks{write_moba(layer,src,&mut o);}write_slice(model.ln_out.weight.as_slice_mut().unwrap(),src,&mut o);write_slice(model.ln_out.bias.as_slice_mut().unwrap(),src,&mut o);write_slice(model.head.weight.as_slice_mut().unwrap(),src,&mut o);assert_eq!(o,src.len());}

#[cfg(test)]
mod tests{use super::*;use crate::model_train_step::ModelTrainStep;use crate::rwkv_model::RwkvModelConfig;#[test]fn optimizer_updates_full_rwkv_model(){let mut model=RwkvModel::new(RwkvModelConfig::new(16,8,2,4),1234);let tokens=[1usize,2,3];let targets=Array1::from_vec(vec![2,3,4]);let step=ModelTrainStep::run(&model,&tokens,&targets);let before=model.head.weight[[0,0]];let mut train=TrainStep::new(&model,1e-3);train.step(&mut model,&step.gradients);assert_ne!(before,model.head.weight[[0,0]]);}#[test]fn optimizer_updates_moba_parameters(){let mut model=RwkvModel::new(RwkvModelConfig::new(16,8,3,4).with_moba(1,2,1),1234);let tokens=[1usize,2,3,4,5,6];let targets=Array1::from_vec(vec![2,3,4,5,6,7]);let step=ModelTrainStep::run(&model,&tokens,&targets);let before=model.moba_blocks[0].att.output.weight[[0,0]];let mut train=TrainStep::new(&model,1e-3);train.step(&mut model,&step.gradients);assert_ne!(before,model.moba_blocks[0].att.output.weight[[0,0]]);}}
