use std::collections::BTreeMap;
use std::fs;
use std::path::Path;
use serde_json::{json, Value};

#[derive(Clone,Debug,Default,PartialEq,Eq)]
pub struct TrainingState{pub step:usize,pub epoch:usize,pub tokens_seen:u64,pub micro_steps:usize,pub optimizer_steps:usize}
impl TrainingState{pub fn new()->Self{Self::default()}pub fn record_micro_step(&mut self,tokens:usize){self.micro_steps+=1;self.tokens_seen=self.tokens_seen.saturating_add(tokens as u64)}pub fn record_optimizer_step(&mut self){self.optimizer_steps+=1;self.step+=1}pub fn record_epoch(&mut self){self.epoch+=1}pub fn reset_accumulation(&mut self){self.micro_steps=0}}

#[derive(Clone,Debug,PartialEq)]
pub struct CheckpointTensor{pub shape:Vec<usize>,pub data:Vec<f32>}
#[derive(Clone,Debug,PartialEq)]
pub struct CheckpointBundle{pub training:TrainingState,pub tensors:BTreeMap<String,CheckpointTensor>,pub optimizer_state:BTreeMap<String,Vec<f32>>,pub tokenizer_metadata:Value,pub rng_state:Option<String>}
impl CheckpointBundle{
 pub fn new(training:TrainingState)->Self{Self{training,tensors:BTreeMap::new(),optimizer_state:BTreeMap::new(),tokenizer_metadata:json!({}),rng_state:None}}
 pub fn insert_tensor(&mut self,name:impl Into<String>,shape:Vec<usize>,data:Vec<f32>){let expected:usize=shape.iter().product();assert_eq!(expected,data.len(),"checkpoint tensor shape does not match data length");self.tensors.insert(name.into(),CheckpointTensor{shape,data});}
 pub fn save(&self,path:impl AsRef<Path>)->Result<(),String>{let tensors=self.tensors.iter().map(|(name,t)| (name.clone(),json!({"shape":t.shape,"data":t.data}))).collect::<serde_json::Map<_,_>>();let optimizer=self.optimizer_state.iter().map(|(k,v)|(k.clone(),json!(v))).collect::<serde_json::Map<_,_>>();let root=json!({"format":"smaul-rust-checkpoint-v1","training":{"step":self.training.step,"epoch":self.training.epoch,"tokens_seen":self.training.tokens_seen,"micro_steps":self.training.micro_steps,"optimizer_steps":self.training.optimizer_steps},"tensors":tensors,"optimizer_state":optimizer,"tokenizer":self.tokenizer_metadata,"rng_state":self.rng_state});let text=serde_json::to_string(&root).map_err(|e|e.to_string())?;fs::write(path,text).map_err(|e|e.to_string())}
 pub fn load(path:impl AsRef<Path>)->Result<Self,String>{let text=fs::read_to_string(path).map_err(|e|e.to_string())?;let root:Value=serde_json::from_str(&text).map_err(|e|e.to_string())?;if root.get("format").and_then(Value::as_str)!=Some("smaul-rust-checkpoint-v1"){return Err("unsupported checkpoint format".into())}let tr=root.get("training").ok_or("checkpoint has no training state")?;let training=TrainingState{step:tr.get("step").and_then(Value::as_u64).ok_or("invalid step")? as usize,epoch:tr.get("epoch").and_then(Value::as_u64).ok_or("invalid epoch")? as usize,tokens_seen:tr.get("tokens_seen").and_then(Value::as_u64).ok_or("invalid tokens_seen")?,micro_steps:tr.get("micro_steps").and_then(Value::as_u64).ok_or("invalid micro_steps")? as usize,optimizer_steps:tr.get("optimizer_steps").and_then(Value::as_u64).ok_or("invalid optimizer_steps")? as usize};let mut tensors=BTreeMap::new();if let Some(obj)=root.get("tensors").and_then(Value::as_object){for(name,value)in obj{let shape=value.get("shape").and_then(Value::as_array).ok_or("invalid tensor shape")?.iter().map(|x|x.as_u64().ok_or("invalid tensor dimension").map(|v|v as usize)).collect::<Result<Vec<_>,_>>()?;let data=value.get("data").and_then(Value::as_array).ok_or("invalid tensor data")?.iter().map(|x|x.as_f64().ok_or("invalid tensor value").map(|v|v as f32)).collect::<Result<Vec<_>,_>>()?;let expected:usize=shape.iter().product();if expected!=data.len(){return Err(format!("tensor '{name}' has invalid element count"));}tensors.insert(name.clone(),CheckpointTensor{shape,data});}}let mut optimizer_state=BTreeMap::new();if let Some(obj)=root.get("optimizer_state").and_then(Value::as_object){for(name,value)in obj{let data=value.as_array().ok_or("invalid optimizer state")?.iter().map(|x|x.as_f64().ok_or("invalid optimizer value").map(|v|v as f32)).collect::<Result<Vec<_>,_>>()?;optimizer_state.insert(name.clone(),data);}}Ok(Self{training,tensors,optimizer_state,tokenizer_metadata:root.get("tokenizer").cloned().unwrap_or_else(||json!({})),rng_state:root.get("rng_state").and_then(Value::as_str).map(str::to_owned)})}
}

#[cfg(test)]
mod tests{use super::*;#[test]fn tracks_training_progress(){let mut s=TrainingState::new();s.record_micro_step(16);s.record_micro_step(8);s.record_optimizer_step();s.record_epoch();assert_eq!(s.tokens_seen,24);assert_eq!(s.step,1);assert_eq!(s.epoch,1);s.reset_accumulation();assert_eq!(s.micro_steps,0)}#[test]fn checkpoint_round_trip(){let p=std::env::temp_dir().join("smaul-rust-checkpoint.json");let mut c=CheckpointBundle::new(TrainingState{step:7,epoch:2,tokens_seen:1234,micro_steps:3,optimizer_steps:7});c.insert_tensor("embedding",vec![2,3],vec![1.,2.,3.,4.,5.,6.]);c.optimizer_state.insert("lion_momentum".into(),vec![0.1,0.2]);c.tokenizer_metadata=json!({"vocab_size":64});c.rng_state=Some("seed:123".into());c.save(&p).unwrap();let d=CheckpointBundle::load(&p).unwrap();assert_eq!(c,d);let _=fs::remove_file(p);}}
