use ndarray::{Array1, Array2, Array4};

pub struct WkvBackward { pub grad_r:Array2<f32>,pub grad_k:Array2<f32>,pub grad_v:Array2<f32>,pub grad_w:Array2<f32>,pub grad_u:Array1<f32>,pub grad_prev:Array4<f32>,pub grad_a:Array2<f32>,pub grad_b:Array2<f32>,pub grad_kk:Array2<f32>,pub grad_aa:Array2<f32> }

pub fn backward(r:&Array2<f32>,k:&Array2<f32>,v:&Array2<f32>,w:&Array2<f32>,u:&Array1<f32>,prev:&Array4<f32>,a:&Array2<f32>,b:&Array2<f32>,kk:&Array2<f32>,aa:&Array2<f32>,next:&Array4<f32>,gstate:&Array4<f32>,grad_output:&Array2<f32>)->WkvBackward {
    let (steps,channels)=r.dim(); let heads=prev.dim().1; let head_size=prev.dim().2; assert_eq!(channels,heads*head_size); let mut gr=Array2::zeros((steps,channels));let mut gk=Array2::zeros((steps,channels));let mut gv=Array2::zeros((steps,channels));let mut gw=Array2::zeros((steps,channels));let mut gu=Array1::zeros(channels);let mut gprev=Array4::zeros(prev.dim());let mut ga=Array2::zeros((steps,channels));let mut gb=Array2::zeros((steps,channels));let mut gkk=Array2::zeros((steps,channels));let mut gaa=Array2::zeros((steps,channels));
    for t in (0..steps).rev(){for h in 0..heads{let base=h*head_size;for i in 0..head_size{let ci=base+i;let mut p=0.0f32;for j in 0..head_size{p+=prev[[0,h,i,j]]*kk[[t,base+j]];}let mut g_p=0.0f32;for j in 0..head_size{let cj=base+j;let gs:f32=gstate[[0,h,i,j]]+grad_output[[t,cj]]*r[[t,ci]];gr[[t,ci]]+=grad_output[[t,cj]]*next[[0,h,i,j]];gw[[t,ci]]+=gs*prev[[0,h,i,j]];gprev[[0,h,i,j]]+=gs*w[[t,ci]];gv[[t,ci]]+=gs*k[[t,cj]];gk[[t,cj]]+=gs*v[[t,ci]];g_p+=-gs*kk[[t,ci]]*a[[t,cj]];ga[[t,cj]]+=-gs*p*kk[[t,ci]];gkk[[t,ci]]+=-gs*p*a[[t,cj]];}gu[ci]+=g_p;gaa[[t,ci]]+=g_p;gb[[t,ci]]+=g_p;}}}
    WkvBackward{grad_r:gr,grad_k:gk,grad_v:gv,grad_w:gw,grad_u:gu,grad_prev:gprev,grad_a:ga,grad_b:gb,grad_kk:gkk,grad_aa:gaa}
}
