use crate::moe::{MoeCmix,MoeRouter};
use rand::{Rng,SeedableRng};
use std::path::{Path,PathBuf};
use crate::checkpoint::PretrainedModel;
use crate::config::RwkvXConfig;
use crate::group_norm::GroupNorm;
use crate::layer_norm::LayerNorm;
use crate::moba_block::{MobaAttention, MobaBlock};
use crate::rwkv_block::RwkvBlock;
use crate::rwkv_cmix::RwkvCmix;
use crate::rwkv_model::RwkvModel;
use crate::rwkv_time_mix::RwkvTimeMix;
use crate::tokenizer::Tokenizer;
use ndarray::Array2;
use std::fs;

fn copy_norm(src:&LayerNorm)->LayerNorm{LayerNorm{normalized_dim:src.normalized_dim,eps:src.eps,weight:src.weight.clone(),bias:src.bias.clone()}}
fn copy_group_norm(src:&GroupNorm)->GroupNorm{GroupNorm::from_weights(src.channels,src.groups,src.eps,src.weight.clone(),src.bias.clone())}
fn copy_time_mix(src:&RwkvTimeMix)->RwkvTimeMix{let mut out=RwkvTimeMix::new_with_qat(src.channels,src.heads,0,1,src.qat_bits);out.x_r=src.x_r.clone();out.x_w=src.x_w.clone();out.x_k=src.x_k.clone();out.x_v=src.x_v.clone();out.x_a=src.x_a.clone();out.x_g=src.x_g.clone();out.w0=src.w0.clone();out.w1=src.w1.clone();out.w2=src.w2.clone();out.a0=src.a0.clone();out.a1=src.a1.clone();out.a2=src.a2.clone();out.v0=src.v0.clone();out.v1=src.v1.clone();out.v2=src.v2.clone();out.g1=src.g1.clone();out.g2=src.g2.clone();out.k_k=src.k_k.clone();out.k_a=src.k_a.clone();out.r_k=src.r_k.clone();out.receptance=src.receptance.clone();out.key=src.key.clone();out.value=src.value.clone();out.output=src.output.clone();out.ln_x=copy_group_norm(&src.ln_x);out.refresh_quantized();out}
fn copy_block(src:&RwkvBlock)->RwkvBlock{let mut out=RwkvBlock::new_with_moe_and_qat(src.channels,src.heads,src.layer_id,src.layer_id+1,false,1,1,0,src.cmix.qat_bits);out.ln0=src.ln0.as_ref().map(copy_norm);out.ln1=copy_norm(&src.ln1);out.ln2=copy_norm(&src.ln2);out.time_mix=copy_time_mix(&src.time_mix);out.cmix=src.cmix.clone();out.moe=None;out}
fn copy_moba(src:&MobaBlock)->MobaBlock{let bits=src.att.receptance.qat_bits;let mut out=MobaBlock::new_with_qat(src.channels,src.att.head_size,src.att.chunk_size,src.att.top_k,src.layer_id,src.ffn.n_layer,bits);out.ln1=copy_norm(&src.ln1);out.ln2=copy_norm(&src.ln2);let mut att=MobaAttention::new_with_qat(src.att.channels,src.att.head_size,src.att.chunk_size,src.att.top_k,bits);att.receptance=crate::linear::Linear::from_weight(src.att.receptance.weight.clone()).with_qat_bits(bits);att.key=crate::linear::Linear::from_weight(src.att.key.weight.clone()).with_qat_bits(bits);att.value=crate::linear::Linear::from_weight(src.att.value.weight.clone()).with_qat_bits(bits);att.output=crate::linear::Linear::from_weight(src.att.output.weight.clone()).with_qat_bits(bits);out.att=att;out.ffn=src.ffn.clone();out}
fn compatible(a:&RwkvXConfig,b:&RwkvXConfig,path:&Path)->Result<(),String>{let pairs=[("n_embd",a.n_embd,b.n_embd),("n_layer",a.n_layer,b.n_layer),("n_moba_layer",a.n_moba_layer,b.n_moba_layer),("head_size",a.head_size,b.head_size),("moba_chunk_size",a.moba_chunk_size,b.moba_chunk_size),("moba_topk",a.moba_topk,b.moba_topk),("qat_bits",a.effective_qat_bits()as usize,b.effective_qat_bits()as usize)];for(name,x,y)in pairs{if x!=y{return Err(format!("{}: {name}={y} does not match base {x}",path.display()))}}Ok(())}
fn branch_experts(model:&RwkvModel,block:usize)->Vec<RwkvCmix>{let b=&model.rwkv_blocks[block];b.moe.as_ref().map(|m|m.experts.clone()).unwrap_or_else(||vec![b.cmix.clone()])}
fn resize_vocab(weight:&Array2<f32>,target:usize,seed:u64)->Array2<f32>{if target<=weight.nrows(){return weight.clone()}let mut out=Array2::zeros((target,weight.ncols()));for r in 0..weight.nrows(){out.row_mut(r).assign(&weight.row(r))}let mean=weight.iter().sum::<f32>()/weight.len().max(1)as f32;let variance=weight.iter().map(|x|(*x-mean).powi(2)).sum::<f32>()/weight.len().max(1)as f32;let std=variance.sqrt().max(0.02);let mut rng=rand::rngs::StdRng::seed_from_u64(seed);for r in weight.nrows()..target{for c in 0..weight.ncols(){let u1=rng.random::<f32>().max(1e-7);let u2=rng.random::<f32>();let z=(-2.0*u1.ln()).sqrt()*(std::f32::consts::TAU*u2).cos();out[[r,c]]=mean+std*z}}out}
fn merged_vocab(base:&Tokenizer,branches:&[Tokenizer])->Vec<String>{let mut out=(0..base.vocab_size()).filter_map(|i|base.id_to_token(i).map(str::to_owned)).collect::<Vec<_>>();let mut seen=out.iter().cloned().collect::<std::collections::HashSet<_>>();for t in branches{for i in 0..t.vocab_size(){if let Some(token)=t.id_to_token(i){if seen.insert(token.to_owned()){out.push(token.to_owned())}}}}out}
pub fn merge(base_dir:impl AsRef<Path>,branch_dirs:&[PathBuf],out_dir:impl AsRef<Path>,top_k:usize)->Result<(),String>{if branch_dirs.is_empty(){return Err("at least one branch is required".into())}if top_k==0{return Err("top_k must be at least 1".into())}let base_dir=base_dir.as_ref();let base=PretrainedModel::load(base_dir)?;let mut branches=Vec::with_capacity(branch_dirs.len());let mut tokenizers=vec![base.tokenizer.clone()];for path in branch_dirs{let branch=PretrainedModel::load(path)?;compatible(&base.config,&branch.config,path)?;tokenizers.push(branch.tokenizer.clone());branches.push(branch)}let counts=branches.iter().map(|m|if m.config.is_moe{m.config.num_experts}else{1}).collect::<Vec<_>>();let num_experts:usize=counts.iter().sum();if top_k>num_experts{return Err(format!("top_k ({top_k}) cannot exceed merged expert count ({num_experts})"))}let vocab=merged_vocab(&base.tokenizer,&tokenizers[1..]);let mut config=base.config.clone();config.vocab_size=vocab.len();config.is_moe=true;config.num_experts=num_experts;config.num_experts_per_tok=top_k;let mut merged=RwkvModel::new(config.to_model_config(),0x4d4f_455f_4d455247);merged.embedding.weight=resize_vocab(&base.model.embedding.weight,vocab.len(),0x454d_4245);merged.head.weight=resize_vocab(&base.model.head.weight,vocab.len(),0x48454144);merged.ln_out=copy_norm(&base.model.ln_out);for i in 0..merged.rwkv_blocks.len(){merged.rwkv_blocks[i]=copy_block(&base.model.rwkv_blocks[i]);let mut experts=Vec::with_capacity(num_experts);for model in &branches{experts.extend(branch_experts(&model.model,i))}let router=MoeRouter::new(config.n_embd,num_experts,top_k,0x524f55544552^i as u64);merged.rwkv_blocks[i].moe=Some(MoeCmix::from_experts(experts,router)?)}for i in 0..merged.moba_blocks.len(){merged.moba_blocks[i]=copy_moba(&base.model.moba_blocks[i])}let tokenizer=Tokenizer::from_vocab(vocab);let output=out_dir.as_ref();fs::create_dir_all(output).map_err(|e|e.to_string())?;let result=PretrainedModel{config,model:merged,tokenizer};result.save(output)?;let meta=serde_json::json!({"engine":"smaul-native merge-moe","base_model":base_dir,"branches":branch_dirs,"branch_expert_counts":counts,"num_experts":num_experts,"top_k":top_k,"tokenizer":{"base_vocab_size":base.tokenizer.vocab_size(),"merged_vocab_size":result.tokenizer.vocab_size()}});fs::write(output.join("merge_config.json"),serde_json::to_string_pretty(&meta).map_err(|e|e.to_string())?).map_err(|e|e.to_string())?;println!("[DONE] merged model -> {} ({} experts, vocab_size={})",output.display(),num_experts,result.tokenizer.vocab_size());Ok(())}
#[cfg(test)]mod tests{use super::*;#[test]fn vocab_merge_preserves_base_ids(){let specials=||["<pad>","<unk>","<bos>","<eos>","<cap>","<upper>"].iter().map(|s|s.to_string()).collect::<Vec<_>>();let mut va=specials();va.extend(["a".to_string(),"b".to_string()]);let mut vb=specials();vb.extend(["b".to_string(),"c".to_string()]);let a=Tokenizer::from_vocab(va.clone());let b=Tokenizer::from_vocab(vb);let merged=merged_vocab(&a,&[b]);assert_eq!(&merged[..va.len()],&va[..],"base ids must keep their positions");assert_eq!(merged.last().unwrap(),"c");assert_eq!(merged.len(),va.len()+1);}}
