use crate::init::uniform;
use crate::rwkv_cmix::RwkvCmix;
use ndarray::{Array1, Array2};

#[derive(Clone,Debug)]pub struct MoeRouter{pub input_size:usize,pub num_experts:usize,pub top_k:usize,pub weight:Array2<f32>}
impl MoeRouter{pub fn new(i:usize,e:usize,k:usize,s:u64)->Self{assert!(i>0&&e>0&&k>0&&k<=e);let q=1.0/(i as f32).sqrt();Self{input_size:i,num_experts:e,top_k:k,weight:uniform(e,i,-q,q,s)}}pub fn from_weight(w:Array2<f32>,k:usize)->Self{assert!(w.nrows()>0&&w.ncols()>0&&k>0&&k<=w.nrows());Self{input_size:w.ncols(),num_experts:w.nrows(),top_k:k,weight:w}}pub fn route(&self,x:&Array2<f32>)->Array2<f32>{let z=x.dot(&self.weight.t());let mut g=Array2::zeros(z.raw_dim());for r in 0..z.nrows(){let mut o:Vec<usize>=(0..self.num_experts).collect();o.sort_unstable_by(|&a,&b|z[[r,b]].total_cmp(&z[[r,a]]));let s=&o[..self.top_k];let m=s.iter().map(|&i|z[[r,i]]).fold(f32::NEG_INFINITY,f32::max);let sum:f32=s.iter().map(|&i|(z[[r,i]]-m).exp()).sum();for&i in s{g[[r,i]]=(z[[r,i]]-m).exp()/sum}}g}pub fn parameter_count(&self)->usize{self.weight.len()}}
#[derive(Clone,Debug)]pub struct MoeCmix{pub experts:Vec<RwkvCmix>,pub router:MoeRouter}
impl MoeCmix{pub fn new(c:usize,l:usize,n:usize,e:usize,k:usize,s:u64)->Self{let experts=(0..e).map(|i|RwkvCmix::new_seeded(c,l,n,s^(i as u64).wrapping_mul(0x9e37_79b9_7f4a_7c15))).collect();Self{experts,router:MoeRouter::new(c,e,k,s)}}pub fn with_qat_3bit(self,on:bool)->Self{self.with_qat_bits(if on{3}else{0})}pub fn with_qat_bits(mut self,b:u8)->Self{for e in&mut self.experts{*e=e.clone().with_qat_bits(b)}self}pub fn from_experts(e:Vec<RwkvCmix>,r:MoeRouter)->Result<Self,String>{if e.is_empty()||e.len()!=r.num_experts||e.iter().any(|x|x.channels!=r.input_size){return Err("invalid MoE expert/router configuration".into())}Ok(Self{experts:e,router:r})}pub fn forward(&self,x:&Array2<f32>,prev:Option<&Array1<f32>>)->(Array2<f32>,Array1<f32>){let g=self.router.route(x);let mut out=Array2::zeros(x.raw_dim());for i in 0..self.experts.len(){let rows:Vec<usize>=(0..x.nrows()).filter(|&r|g[[r,i]]!=0.0).collect();if rows.is_empty(){continue}let y=self.experts[i].forward_rows(x,prev,&rows);for(a,&r)in rows.iter().enumerate(){for c in 0..x.ncols(){out[[r,c]]+=g[[r,i]]*y[[a,c]]}}}(out,x.row(x.nrows()-1).to_owned())}pub fn parameter_count(&self)->usize{self.router.parameter_count()+self.experts.iter().map(RwkvCmix::parameter_count).sum::<usize>()}}
#[cfg(test)]mod tests_moe{use super::*;#[test]fn qat_width_reaches_experts(){for b in[2u8,3,4,8]{let m=MoeCmix::new(8,0,4,3,2,7).with_qat_bits(b);assert!(m.experts.iter().all(|e|e.qat_bits==b));}}}


// ===== moe_backward =====

pub struct MoeBackward{pub grad_input:Array2<f32>,pub grad_prev:Array1<f32>,pub grad_router:Array2<f32>,pub grad_x_k:Vec<Array1<f32>>,pub grad_key:Vec<Array2<f32>>,pub grad_value:Vec<Array2<f32>>}

pub fn backward(moe:&MoeCmix,input:&Array2<f32>,prev:Option<&Array1<f32>>,grad_output:&Array2<f32>)->MoeBackward{
 assert_eq!(input.ncols(),moe.router.input_size);assert_eq!(grad_output.dim(),input.dim());let gates=moe.router.route(input);let mut grad_input=Array2::zeros(input.raw_dim());let mut grad_router=Array2::zeros(moe.router.weight.raw_dim());let mut grad_prev=Array1::zeros(input.ncols());let mut grad_x_k=moe.experts.iter().map(|e|Array1::zeros(e.x_k.len())).collect::<Vec<_>>();let mut grad_key=moe.experts.iter().map(|e|Array2::zeros(e.key.raw_dim())).collect::<Vec<_>>();let mut grad_value=moe.experts.iter().map(|e|Array2::zeros(e.value.raw_dim())).collect::<Vec<_>>();
 for expert_id in 0..moe.experts.len(){let rows:Vec<usize>=(0..input.nrows()).filter(|&row|gates[[row,expert_id]]!=0.0).collect();if rows.is_empty(){continue;}let mut expert_grad=Array2::zeros(input.raw_dim());for&row in &rows{for col in 0..input.ncols(){expert_grad[[row,col]]=grad_output[[row,col]]*gates[[row,expert_id]];}}let expert=&moe.experts[expert_id];let(key,value)=expert.effective_weights();let result=crate::rwkv_cmix::backward(input,prev,&expert_grad,&expert.x_k,&key,&value);grad_input+=&result.grad_input;grad_prev+=&result.grad_prev;grad_x_k[expert_id]+=&result.grad_x_k;grad_key[expert_id]+=&result.grad_key;grad_value[expert_id]+=&result.grad_value;}
 for row in 0..input.nrows(){let selected:Vec<usize>=(0..moe.experts.len()).filter(|&i|gates[[row,i]]>0.0).collect();if selected.is_empty(){continue;}let mut scores=Vec::with_capacity(selected.len());for&expert_id in &selected{let out=moe.experts[expert_id].forward_rows(input,prev,&[row]);scores.push(grad_output.row(row).dot(&out.row(0)));}let expected=selected.iter().enumerate().map(|(i,&expert_id)|gates[[row,expert_id]]*scores[i]).sum::<f32>();for(i,&expert_id)in selected.iter().enumerate(){let dlogit=gates[[row,expert_id]]*(scores[i]-expected);for col in 0..input.ncols(){grad_router[[expert_id,col]]+=dlogit*input[[row,col]];grad_input[[row,col]]+=dlogit*moe.router.weight[[expert_id,col]];}}}
 MoeBackward{grad_input,grad_prev,grad_router,grad_x_k,grad_key,grad_value}
}
pub fn router_parameter_count(router:&MoeRouter)->usize{router.weight.len()}
#[cfg(test)]mod tests_moe_backward{use super::*;use MoeCmix;use ndarray::Array2;#[test]fn backward_shapes(){let moe=MoeCmix::new(8,0,4,3,2,7);let x=Array2::<f32>::ones((4,8));let result=backward(&moe,&x,None,&Array2::ones((4,8)));assert_eq!(result.grad_input.dim(),x.dim());assert_eq!(result.grad_router.dim(),(3,8));assert_eq!(result.grad_key.len(),3);}#[test]fn input_gradient_matches_finite_difference_away_from_route_ties(){let moe=MoeCmix::new(4,0,2,2,1,19);let x=Array2::from_shape_fn((2,4),|(r,c)|0.13+r as f32*0.41+c as f32*0.17);let grad=backward(&moe,&x,None,&Array2::ones((2,4))).grad_input;let eps=1e-3_f32;for&(row,col)in&[(0usize,0usize),(0,2),(1,1)]{let mut plus=x.clone();let mut minus=x.clone();plus[[row,col]]+=eps;minus[[row,col]]-=eps;let(yp,_)=moe.forward(&plus,None);let(ym,_)=moe.forward(&minus,None);let numeric=(yp.sum()-ym.sum())/(2.0*eps);assert!((numeric-grad[[row,col]]).abs()<0.2,"gradient mismatch at ({row},{col}): analytic={} numeric={numeric}",grad[[row,col]]);}}#[test]fn qat_moe_backward_uses_quantized_experts(){let moe=MoeCmix::new(4,0,2,2,1,19).with_qat_3bit(true);let x=Array2::from_shape_fn((2,4),|(r,c)|0.07+r as f32*0.2+c as f32*0.11);let result=backward(&moe,&x,None,&Array2::ones((2,4)));assert!(result.grad_input.iter().all(|v|v.is_finite()));}}
