use ndarray::Array2;

pub const QAT_3BIT_MIN:i8=-4;
pub const QAT_3BIT_MAX:i8=3;
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub enum Bits{Fp2,Fp4,Fp8}
impl Bits{pub fn from_bits(bits:u8)->Result<Self,String>{match bits{2=>Ok(Self::Fp2),4=>Ok(Self::Fp4),8=>Ok(Self::Fp8),_=>Err("bits must be 2, 4, or 8".into())}}pub fn bits(self)->u8{match self{Self::Fp2=>2,Self::Fp4=>4,Self::Fp8=>8}}fn levels(self)->&'static[f32]{match self{Self::Fp2=>&[-1.,0.,1.],Self::Fp4=>&[-2.,-1.,-.5,-.25,0.,.25,.5,1.,2.],Self::Fp8=>&[]}}}
fn fp8_code(v:f32)->u8{const MAX:f32=448.;if v.is_nan(){return 0x7f}if v==0.{return if v.is_sign_negative(){0x80}else{0}}let s=if v.is_sign_negative(){0x80}else{0};let x=v.abs();if x.is_infinite()||x>=MAX{return s|0x7e}let mut e=x.log2().floor()as i32;if e< -6{e=-6}if e>8{e=8}let base=2f32.powi(e);let mut m=((x/base-1.)*8.).round()as i32;if m>=8{m=0;e+=1}if e>8{return s|0x7e}if e==8&&m>6{return s|0x7e}s|(((e+7)as u8)<<3)|(m.clamp(0,7)as u8)}
fn fp8_value(c:u8)->f32{if c==0x7f||c==0xff{return f32::NAN}if c&0x7f==0{return if c&0x80!=0{-0.}else{0.}}let s=if c&0x80!=0{-1.}else{1.};let e=((c>>3)&15)as i32-7;s*2f32.powi(e)*(1.+(c&7)as f32/8.)}
fn fp8_fake(v:f32)->f32{if v==0.{v}else{fp8_value(fp8_code(v))}}
pub fn quantize_codes(x:&Array2<f32>,bits:Bits)->(Array2<u8>,Vec<f32>){assert_ne!(bits,Bits::Fp8);let levels=bits.levels();let mut codes=Array2::zeros(x.raw_dim());let mut scales=vec![0.;x.nrows()];for r in 0..x.nrows(){let mut s=x.row(r).iter().map(|v|v.abs()).fold(0.,f32::max);if s<f32::EPSILON{s=1.}scales[r]=s;for c in 0..x.ncols(){let v=x[[r,c]]/s;let mut best=0;let mut d=f32::INFINITY;for(i,l)in levels.iter().enumerate(){let z=(v-l).abs();if z<d{d=z;best=i}}codes[[r,c]]=best as u8}}(codes,scales)}
pub fn dequantize(codes:&Array2<u8>,scales:&[f32],bits:Bits)->Array2<f32>{assert_ne!(bits,Bits::Fp8);assert_eq!(codes.nrows(),scales.len());let levels=bits.levels();Array2::from_shape_fn(codes.raw_dim(),|(r,c)|levels[codes[[r,c]]as usize]*scales[r])}
pub fn fake_quantize(x:&Array2<f32>,bits:Bits)->Array2<f32>{match bits{Bits::Fp8=>x.mapv(fp8_fake),Bits::Fp2|Bits::Fp4=>{let(c,s)=quantize_codes(x,bits);dequantize(&c,&s,bits)}}}
pub fn quantized_linear(input:&Array2<f32>,weight:&Array2<f32>,bits:Bits)->Array2<f32>{assert_eq!(input.ncols(),weight.ncols());input.dot(&fake_quantize(weight,bits).t())}
pub fn pack_3bit(codes:&[u8])->Vec<u8>{let mut out=Vec::with_capacity((codes.len()*3+7)/8);let(mut a,mut n)=(0u8,0u8);for&c in codes{for sh in[2u8,1,0]{a|=((c&7)>>sh)<<(7-n);n+=1;if n==8{out.push(a);a=0;n=0}}}if n>0{out.push(a)}out}
pub fn unpack_3bit(packed:&[u8],numel:usize)->Vec<u8>{assert!(packed.len()*8>=numel*3);let mut out=Vec::with_capacity(numel);for i in 0..numel*3{let b=(packed[i/8]>>(7-i%8))&1;match i%3{0=>out.push(b<<2),1=>*out.last_mut().unwrap()|=b<<1,_=>*out.last_mut().unwrap()|=b}}out}
pub fn pack_lowbit(codes:&[u8],bits:Bits)->Vec<u8>{match bits{Bits::Fp2=>{let mut out=Vec::with_capacity((codes.len()*2+7)/8);let(mut a,mut n)=(0u8,0);for&c in codes{a|=(c&3)<<(6-n);n+=2;if n==8{out.push(a);a=0;n=0}}if n>0{out.push(a)}out},Bits::Fp4=>codes.chunks(2).map(|c|((c[0]&15)<<4)|(c.get(1).copied().unwrap_or(0)&15)).collect(),Bits::Fp8=>codes.to_vec()}}
pub fn unpack_lowbit(packed:&[u8],numel:usize,bits:Bits)->Vec<u8>{match bits{Bits::Fp2=>{assert!(packed.len()*4>=numel);(0..numel).map(|i|(packed[i/4]>>(6-2*(i%4)))&3).collect()},Bits::Fp4=>{assert!(packed.len()*2>=numel);(0..numel).map(|i|if i%2==0{packed[i/2]>>4&15}else{packed[i/2]&15}).collect()},Bits::Fp8=>packed[..numel].to_vec()}}
pub fn quantize_weight(weight:&Array2<f32>,bits:Bits)->(Vec<u8>,Vec<f32>){match bits{Bits::Fp8=>(weight.iter().map(|&v|fp8_code(v)).collect(),vec![1.]),Bits::Fp2|Bits::Fp4=>{let(c,s)=quantize_codes(weight,bits);(pack_lowbit(c.as_slice().unwrap(),bits),s)}}}
pub fn dequantize_weight(packed:&[u8],scales:&[f32],shape:(usize,usize),bits:Bits)->Array2<f32>{match bits{Bits::Fp8=>Array2::from_shape_vec(shape,(0..shape.0*shape.1).map(|i|fp8_value(packed[i])).collect()).unwrap(),Bits::Fp2|Bits::Fp4=>{assert_eq!(scales.len(),shape.0);let c=unpack_lowbit(packed,shape.0*shape.1,bits);let l=bits.levels();Array2::from_shape_fn(shape,|(r,col)|l[c[r*shape.1+col]as usize]*scales[r])}}}
pub fn quantize_weight_3bit(weight:&Array2<f32>)->(Vec<u8>,Vec<f32>){let mut c=Vec::with_capacity(weight.len());let mut s=Vec::with_capacity(weight.nrows());for row in weight.rows(){let m=row.iter().map(|v|v.abs()).fold(0.,f32::max);let sc=(m/QAT_3BIT_MAX as f32).max(f32::EPSILON);s.push(sc);for&v in row{let q=(v/sc).round().clamp(QAT_3BIT_MIN as f32,QAT_3BIT_MAX as f32)as i8;c.push((q-QAT_3BIT_MIN)as u8)}}(pack_3bit(&c),s)}
pub fn dequantize_weight_3bit(packed:&[u8],scales:&[f32],shape:(usize,usize))->Array2<f32>{let(r,c)=shape;assert_eq!(scales.len(),r);let q=unpack_3bit(packed,r*c);Array2::from_shape_fn(shape,|(i,j)|((q[i*c+j]as i8+QAT_3BIT_MIN)as f32)*scales[i])}
#[derive(Clone,Debug)]pub struct QatLinear{pub weight:Array2<f32>,pub bits:Bits}
impl QatLinear{pub fn new(weight:Array2<f32>,bits:Bits)->Self{assert!(!weight.is_empty());Self{weight,bits}}pub fn forward(&self,input:&Array2<f32>)->Array2<f32>{quantized_linear(input,&self.weight,self.bits)}pub fn convert(&self)->PackedLinear{let(p,s)=quantize_weight(&self.weight,self.bits);PackedLinear{packed:p,scales:s,shape:self.weight.dim(),bits:self.bits}}}
#[derive(Clone,Debug)]pub struct PackedLinear{pub packed:Vec<u8>,pub scales:Vec<f32>,pub shape:(usize,usize),pub bits:Bits}
impl PackedLinear{pub fn forward(&self,input:&Array2<f32>)->Array2<f32>{input.dot(&dequantize_weight(&self.packed,&self.scales,self.shape,self.bits).t())}}
#[derive(Clone,Debug)]pub struct QatLinear3Bit{pub weight:Array2<f32>,pub signed_activation:bool,pub activation_min:f32,pub activation_max:f32,pub momentum:f32}
impl QatLinear3Bit{pub fn new(weight:Array2<f32>,signed_activation:bool)->Self{assert!(weight.nrows()>0&&weight.ncols()>0);Self{weight,signed_activation,activation_min:0.,activation_max:0.,momentum:.1}}pub fn observe(&mut self,input:&Array2<f32>){if input.is_empty(){return}let min=input.iter().copied().fold(f32::INFINITY,f32::min);let max=input.iter().copied().fold(f32::NEG_INFINITY,f32::max);if self.activation_min==0.&&self.activation_max==0.{self.activation_min=min;self.activation_max=max}else{self.activation_min=(1.-self.momentum)*self.activation_min+self.momentum*min;self.activation_max=(1.-self.momentum)*self.activation_max+self.momentum*max}}pub fn fake_quantize_activation(&self,input:&Array2<f32>)->Array2<f32>{if self.signed_activation{let m=self.activation_min.abs().max(self.activation_max.abs());let s=(m/QAT_3BIT_MAX as f32).max(f32::EPSILON);return input.mapv(|v|(v/s).round().clamp(QAT_3BIT_MIN as f32,QAT_3BIT_MAX as f32)*s)}let r=(self.activation_max-self.activation_min).max(f32::EPSILON);input.mapv(|v|{let q=((v-self.activation_min)/r).clamp(0.,1.)*7.;self.activation_min+q.round()*r/7.})}pub fn forward(&mut self,input:&Array2<f32>)->Array2<f32>{self.observe(input);let a=self.fake_quantize_activation(input);let(p,s)=quantize_weight_3bit(&self.weight);a.dot(&dequantize_weight_3bit(&p,&s,self.weight.dim()).t())}pub fn convert(&self)->QuantizedLinear3Bit{let(p,s)=quantize_weight_3bit(&self.weight);QuantizedLinear3Bit{packed:p,scales:s,shape:self.weight.dim()}}}
#[derive(Clone,Debug)]pub struct QuantizedLinear3Bit{pub packed:Vec<u8>,pub scales:Vec<f32>,pub shape:(usize,usize)}impl QuantizedLinear3Bit{pub fn forward(&self,input:&Array2<f32>)->Array2<f32>{input.dot(&dequantize_weight_3bit(&self.packed,&self.scales,self.shape).t())}}
#[cfg(test)]mod tests{use super::*;use ndarray::array;#[test]fn bit_modes_are_supported(){assert_eq!(Bits::from_bits(2).unwrap().bits(),2);assert_eq!(Bits::from_bits(4).unwrap().bits(),4);assert_eq!(Bits::from_bits(8).unwrap().bits(),8);assert!(Bits::from_bits(3).is_err())}#[test]fn fp2_round_trip_uses_three_levels(){let x=array![[-2.,0.],[.5,2.]];let q=fake_quantize(&x,Bits::Fp2);assert_eq!(q[[0,0]],-2.);assert_eq!(q[[0,1]],0.);assert_eq!(q[[1,0]],0.);assert_eq!(q[[1,1]],2.)}#[test]fn fp4_quantization_has_expected_shape(){let x=array![[1.,-.5,.2]];assert_eq!(fake_quantize(&x,Bits::Fp4).dim(),x.dim())}#[test]fn fp8_quantization_is_finite(){let q=fake_quantize(&array![[1.,-.5,.2]],Bits::Fp8);assert!(q.iter().all(|v|v.is_finite()));assert!((q[[0,0]]-1.).abs()<.01)}#[test]fn fp8_packed_storage_is_one_byte_per_value(){let x=array![[1.,-.5,.2],[2.,-1.,0.]];let(p,s)=quantize_weight(&x,Bits::Fp8);assert_eq!(p.len(),x.len());assert_eq!(s,vec![1.]);let r=dequantize_weight(&p,&s,x.dim(),Bits::Fp8);assert_eq!(r[[1,2]],0.)}#[test]fn quantized_linear_has_expected_shape(){let x=array![[1.,2.,3.]];let w=array![[1.,0.,0.],[0.,1.,0.]];assert_eq!(quantized_linear(&x,&w,Bits::Fp4).shape(),&[1,2])}#[test]fn packed_lowbit_round_trips(){let c=vec![0,1,2,3,0,1,2,3,2,1,0];for b in[Bits::Fp2,Bits::Fp4]{assert_eq!(unpack_lowbit(&pack_lowbit(&c,b),c.len(),b),c.iter().map(|x|if b==Bits::Fp2{x&3}else{x&15}).collect::<Vec<_>>())}}#[test]fn pack_3bit_round_trips(){let c=vec![0,1,2,3,4,5,6,7,0,7,3];assert_eq!(unpack_3bit(&pack_3bit(&c),c.len()),c)}#[test]fn qat_3bit_weight_preserves_shape(){let w=array![[1.,-2.],[.5,3.]];let(p,s)=quantize_weight_3bit(&w);assert_eq!(dequantize_weight_3bit(&p,&s,w.dim()).dim(),w.dim());assert_eq!(s.len(),w.nrows())}#[test]fn qat_linear_observes_and_converts(){let mut l=QatLinear3Bit::new(array![[1.,0.],[0.,1.]],true);assert_eq!(l.forward(&array![[1.,-1.]]).dim(),(1,2))}}
