use crate::layer_norm::LayerNorm;
use crate::moe::MoeCmix;
use crate::rwkv_cmix::RwkvCmix;
use crate::rwkv_time_mix::RwkvTimeMix;
use crate::rwkv_block_full_tape::RwkvBlockFullTape;
use ndarray::{Array1,Array2,Array4};
#[derive(Clone)]pub struct RwkvBlockState{pub time_state:Array4<f32>,pub time_prev:Array1<f32>,pub cmix_prev:Array1<f32>,pub v_first:Option<Array2<f32>>}
pub struct RwkvBlock{pub channels:usize,pub heads:usize,pub layer_id:usize,pub ln0:Option<LayerNorm>,pub ln1:LayerNorm,pub ln2:LayerNorm,pub time_mix:RwkvTimeMix,pub cmix:RwkvCmix,pub moe:Option<MoeCmix>}
impl RwkvBlock{pub fn new(c:usize,h:usize,l:usize,n:usize)->Self{Self::new_with_moe_and_qat(c,h,l,n,false,1,1,0,0)}pub fn new_with_moe(c:usize,h:usize,l:usize,n:usize,m:bool,e:usize,k:usize,s:u64)->Self{Self::new_with_moe_and_qat_seed(c,h,l,n,m,e,k,s,0)}pub fn new_with_moe_and_qat(c:usize,h:usize,l:usize,n:usize,m:bool,e:usize,k:usize,s:u64,bits:u8)->Self{Self::new_with_moe_and_qat_seed(c,h,l,n,m,e,k,s,bits)}fn new_with_moe_and_qat_seed(c:usize,h:usize,l:usize,n:usize,m:bool,e:usize,k:usize,s:u64,bits:u8)->Self{assert!(c>0&&h>0);assert_eq!(c%h,0);let cmix=RwkvCmix::new_seeded(c,l,n,s^0x434d_4958).with_qat_bits(bits);let moe=if m{Some(MoeCmix::new(c,l,n,e,k,s).with_qat_bits(bits))}else{None};Self{channels:c,heads:h,layer_id:l,ln0:if l==0{Some(LayerNorm::new(c,1e-5))}else{None},ln1:LayerNorm::new(c,1e-5),ln2:LayerNorm::new(c,1e-5),time_mix:RwkvTimeMix::new_with_qat(c,h,l,n,bits),cmix,moe}}
pub fn forward(&self,x:&Array2<f32>,state:Option<&RwkvBlockState>,vf:Option<&Array2<f32>>)->(Array2<f32>,RwkvBlockState){let input=match&self.ln0{Some(n)=>n.forward(x),None=>x.clone()};let ti=self.ln1.forward(&input);let ts=state.map(|s|s.time_state.clone());let tp=state.map(|s|s.time_prev.clone());let iv=vf.cloned().or_else(||state.and_then(|s|s.v_first.clone()));let(to,nts,ntp,nv)=self.time_mix.forward(&ti,ts,tp,iv);let residual=&input+&to;let ci=self.ln2.forward(&residual);let cp=state.map(|s|&s.cmix_prev);let(co,ncp)=match&self.moe{Some(m)=>m.forward(&ci,cp),None=>self.cmix.forward(&ci,cp)};(&residual+&co,RwkvBlockState{time_state:nts,time_prev:ntp,cmix_prev:ncp,v_first:Some(nv)})}
pub fn forward_with_full_tape(&self,x:&Array2<f32>,state:Option<&RwkvBlockState>,vf:Option<&Array2<f32>>)->(Array2<f32>,RwkvBlockState,RwkvBlockFullTape){let input=x.clone();let(l0i,l0o)=match&self.ln0{Some(n)=>(Some(input.clone()),Some(n.forward(&input))),None=>(None,None)};let bi=l0o.clone().unwrap_or_else(||input.clone());let l1i=bi.clone();let l1o=self.ln1.forward(&l1i);let ts=state.map(|s|s.time_state.clone());let tp=state.map(|s|s.time_prev.clone());let iv=vf.cloned().or_else(||state.and_then(|s|s.v_first.clone()));let(to,nts,ntp,nv,tt)=self.time_mix.forward_with_tape(&l1o,ts,tp,iv);let residual=&bi+&to;let l2i=residual.clone();let l2o=self.ln2.forward(&l2i);let cp=state.map(|s|s.cmix_prev.clone()).unwrap_or_else(||Array1::zeros(self.channels));let(co,ncp,mixed,pre,hidden)=match&self.moe{Some(m)=>{let(o,p)=m.forward(&l2o,Some(&cp));(o,p,l2o.clone(),Array2::zeros((l2o.nrows(),self.channels*4)),Array2::zeros((l2o.nrows(),self.channels*4)))}None=>{let mut m=l2o.clone();for t in 0..m.nrows(){for c in 0..self.channels{let p=if t==0{cp[c]}else{l2o[[t-1,c]]};m[[t,c]]=l2o[[t,c]]+(p-l2o[[t,c]])*self.cmix.x_k[c]}}let(k,v)=self.cmix.effective_weights();let p=m.dot(&k);let h=p.mapv(|v|v.max(0.0).powi(2));(h.dot(&v),l2o.row(l2o.nrows()-1).to_owned(),m,p,h)}};let out=&residual+&co;let ns=RwkvBlockState{time_state:nts,time_prev:ntp,cmix_prev:ncp,v_first:Some(nv)};let mut tape=RwkvBlockFullTape::new(input,tt,ns.clone());tape.initial_state=state.cloned();tape.ln0_input=l0i;tape.ln0_output=l0o;tape.ln1_input=l1i;tape.ln1_output=l1o;tape.residual=residual;tape.ln2_input=l2i;tape.ln2_output=l2o.clone();tape.cmix_input=l2o;tape.cmix_prev=cp;tape.cmix_mixed=mixed;tape.cmix_pre=pre;tape.cmix_hidden=hidden;tape.cmix_output=co;tape.output=out.clone();(out,ns,tape)}pub fn parameter_count(&self)->usize{let n=self.ln0.as_ref().map_or(0,|x|x.weight.len()+x.bias.len())+self.ln1.weight.len()+self.ln1.bias.len()+self.ln2.weight.len()+self.ln2.bias.len();n+self.time_mix.parameter_count()+match&self.moe{Some(m)=>m.parameter_count(),None=>self.cmix.parameter_count()}}}
#[cfg(test)]mod tests{use super::*;#[test]fn qat_widths_construct(){for b in[0u8,2,3,4,8]{let x=RwkvBlock::new_with_moe_and_qat(16,2,0,4,false,1,1,1,b);assert_eq!(x.cmix.qat_bits,b);}}}
